/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica8ut2;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Juego extends javax.swing.JFrame {
    private String nombre; //Nombre que introducirá el usuario
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        juego(); //Iniciamos el juego
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    private void juego(){
       nombre=JOptionPane.showInputDialog(this,"Introduce tu nombre","Nombre de usuario",JOptionPane.QUESTION_MESSAGE); //Pedimos el nombre al usuario
       JOptionPane.showMessageDialog(this,"¿Qué personaje quieres ser, "+nombre+"?","Elección de personaje",JOptionPane.INFORMATION_MESSAGE);
       ElegirPersonaje elegirPersonaje=new ElegirPersonaje(this,true); //Creamos el diálogo de elección de personaje
       elegirPersonaje.setVisible(true);
    }
    public void confirmarPersonaje(String personaje){
        int resultado=JOptionPane.showConfirmDialog(this,nombre+",has elegido al caballo, muy buena elección, pero ¿estás completamente seguro de tu elección?","Confirmación",JOptionPane.YES_NO_OPTION);
        if(resultado==JOptionPane.YES_OPTION){ //Si el usuario elige que sí
            JOptionPane.showMessageDialog(this,"Has elegido el "+personaje+", "+nombre+" bienvenido a MathGames","Confirmación personaje",JOptionPane.INFORMATION_MESSAGE); //Le damos la bienvenida
        }else if (resultado==JOptionPane.NO_OPTION){ //Si el usuario elige que no
            JOptionPane.showMessageDialog(this,"¿Tu elección no es "+personaje+"? Entonces, ¿Qué personaje quieres ser?","Elección de personaje",JOptionPane.INFORMATION_MESSAGE);
            ElegirPersonaje elegirPersonaje=new ElegirPersonaje(this,true); //Volvemos a darle la opción de elegir personaje
            elegirPersonaje.setVisible(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
