/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad4_1.gui;

import actividad4_1.logica.LogicaNegocio;
import actividad4_1.logica.MiMouseListener;
import actividad4_1.logica.Pelicula;
import java.applet.AudioClip;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.UIManager;

/**
 *
 * @author Danim2205
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    AudioClip sound=java.applet.Applet.newAudioClip(getClass().getResource("/actividad4_1/sounds/Money.wav"));
    private List<Pelicula>peliculas=LogicaNegocio.getListaPeliculas();
    private Pelicula peliculaActual;
    private int asientos[]=new int[0];
    private int sala=0;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/actividad4_1/imgs/Logo.png")).getImage());
        establecerColoresJOptionPane();
        ((DefaultEditor) jSpinnerNumeroAsientos.getEditor()).getTextField().setEditable(false);
        LogicaNegocio.crearPeliculas(); //Creamos las películas por defecto
        añadirListenersCartelera(); //Añadimos los listeners a todos los labels
        actualizarPeliculaActual(); //Ponemos los valores iniciales
       
    }

    private void establecerColoresJOptionPane(){
        UIManager UI=new UIManager();
        UIManager.put("control", Color.WHITE); //Cambia todos los fondos del JOptionPane
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelComprarEntrada = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabelPrecio = new javax.swing.JLabel();
        jComboBoxPelicula = new javax.swing.JComboBox<>();
        jLabelPelicula = new javax.swing.JLabel();
        jLabelNumeroAsientos = new javax.swing.JLabel();
        jSpinnerNumeroAsientos = new javax.swing.JSpinner();
        jCheckBoxPrimeraFila = new javax.swing.JCheckBox();
        jButtonGenerarAsientos = new javax.swing.JButton();
        jPanelDatos1 = new javax.swing.JPanel();
        jLabelAsientos = new javax.swing.JLabel();
        jButtonConfirmarCompra = new javax.swing.JButton();
        jLabelSala = new javax.swing.JLabel();
        jLabelLogo2 = new javax.swing.JLabel();
        jLabelPeliculaActual = new javax.swing.JLabel();
        jPanelVerCartelera = new javax.swing.JPanel();
        jPanelPeliculas = new javax.swing.JPanel();
        jLabelTitanic = new javax.swing.JLabel();
        jLabelMillionDollarBaby = new javax.swing.JLabel();
        jLabelMinions = new javax.swing.JLabel();
        jLabelTheBoogeyman = new javax.swing.JLabel();
        jLabelJurassicPark = new javax.swing.JLabel();
        jLabelInsidious3 = new javax.swing.JLabel();
        jLabelCastilloAmbulante = new javax.swing.JLabel();
        jLabelElPadrino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N

        jPanelComprarEntrada.setBackground(new java.awt.Color(255, 255, 255));
        jPanelComprarEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Rockwell", 1, 64)); // NOI18N
        jLabelTitulo.setText("CINE RIBERA");
        jPanelComprarEntrada.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Logo.png"))); // NOI18N
        jPanelComprarEntrada.add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jPanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Configure su compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 18))); // NOI18N
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrecio.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelPrecio.setText("Precio: ");
        jPanelDatos.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jComboBoxPelicula.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jComboBoxPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titanic", "Million Dollar Baby", "Los Minions", "The Boogeyman", "Jurassic Park", "Insidious 3", "El Castillo Ambulante", "El Padrino" }));
        jComboBoxPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeliculaActionPerformed(evt);
            }
        });
        jPanelDatos.add(jComboBoxPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 44, -1, -1));

        jLabelPelicula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabelPelicula.setText("Película a ver:");
        jPanelDatos.add(jLabelPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 47, -1, -1));

        jLabelNumeroAsientos.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabelNumeroAsientos.setText("Número de asientos:");
        jPanelDatos.add(jLabelNumeroAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 108, -1, -1));

        jSpinnerNumeroAsientos.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jSpinnerNumeroAsientos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        jSpinnerNumeroAsientos.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerNumeroAsientos, ""));
        jSpinnerNumeroAsientos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerNumeroAsientosStateChanged(evt);
            }
        });
        jPanelDatos.add(jSpinnerNumeroAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 105, 51, -1));

        jCheckBoxPrimeraFila.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPrimeraFila.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jCheckBoxPrimeraFila.setText("Asientos en primera fila");
        jPanelDatos.add(jCheckBoxPrimeraFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 165, -1, -1));

        jButtonGenerarAsientos.setBackground(new java.awt.Color(0, 0, 0));
        jButtonGenerarAsientos.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButtonGenerarAsientos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerarAsientos.setText("GENERAR ASIENTOS");
        jButtonGenerarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarAsientosActionPerformed(evt);
            }
        });
        jPanelDatos.add(jButtonGenerarAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 360, -1));

        jPanelComprarEntrada.add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 520, 310));

        jPanelDatos1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Confirmar compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 18))); // NOI18N
        jPanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAsientos.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelAsientos.setText("ASIENTOS: ");
        jPanelDatos1.add(jLabelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButtonConfirmarCompra.setBackground(new java.awt.Color(0, 0, 0));
        jButtonConfirmarCompra.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButtonConfirmarCompra.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmarCompra.setText("CONFIRMAR COMPRA");
        jButtonConfirmarCompra.setEnabled(false);
        jButtonConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarCompraActionPerformed(evt);
            }
        });
        jPanelDatos1.add(jButtonConfirmarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 360, -1));

        jLabelSala.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelSala.setText("SALA: ");
        jPanelDatos1.add(jLabelSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jLabelSala.getAccessibleContext().setAccessibleName("SALA:");

        jPanelComprarEntrada.add(jPanelDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 520, 160));

        jLabelLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Logo.png"))); // NOI18N
        jPanelComprarEntrada.add(jLabelLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabelPeliculaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Titanic.png"))); // NOI18N
        jPanelComprarEntrada.add(jLabelPeliculaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jTabbedPane.addTab("Comprar entrada", jPanelComprarEntrada);

        jPanelVerCartelera.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVerCartelera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPeliculas.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelPeliculas.setLayout(new java.awt.GridLayout(2, 4));

        jLabelTitanic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Titanic.png"))); // NOI18N
        jLabelTitanic.setName("Titanic"); // NOI18N
        jPanelPeliculas.add(jLabelTitanic);

        jLabelMillionDollarBaby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Million Dollar Baby.png"))); // NOI18N
        jLabelMillionDollarBaby.setName("Million Dollar Baby"); // NOI18N
        jPanelPeliculas.add(jLabelMillionDollarBaby);

        jLabelMinions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Los Minions.png"))); // NOI18N
        jLabelMinions.setName("Los Minions"); // NOI18N
        jPanelPeliculas.add(jLabelMinions);

        jLabelTheBoogeyman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/The Boogeyman.png"))); // NOI18N
        jLabelTheBoogeyman.setName("The Boogeyman"); // NOI18N
        jPanelPeliculas.add(jLabelTheBoogeyman);

        jLabelJurassicPark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Jurassic Park.png"))); // NOI18N
        jLabelJurassicPark.setName("Jurassic Park"); // NOI18N
        jPanelPeliculas.add(jLabelJurassicPark);

        jLabelInsidious3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Insidious 3.png"))); // NOI18N
        jLabelInsidious3.setName("Insidious 3"); // NOI18N
        jPanelPeliculas.add(jLabelInsidious3);

        jLabelCastilloAmbulante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/El Castillo Ambulante.png"))); // NOI18N
        jLabelCastilloAmbulante.setName("El Castillo Ambulante"); // NOI18N
        jPanelPeliculas.add(jLabelCastilloAmbulante);

        jLabelElPadrino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/El Padrino.png"))); // NOI18N
        jLabelElPadrino.setName("El Padrino"); // NOI18N
        jPanelPeliculas.add(jLabelElPadrino);

        jPanelVerCartelera.add(jPanelPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 8, -1, -1));

        jTabbedPane.addTab("Ver cartelera", jPanelVerCartelera);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));
        jTabbedPane.getAccessibleContext().setAccessibleName("Comprar entrada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeliculaActionPerformed
        actualizarPeliculaActual();
    }//GEN-LAST:event_jComboBoxPeliculaActionPerformed

    private void jSpinnerNumeroAsientosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNumeroAsientosStateChanged
        actualizarPeliculaActual();
    }//GEN-LAST:event_jSpinnerNumeroAsientosStateChanged

    private void jButtonGenerarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarAsientosActionPerformed
        jLabelAsientos.setText("ASIENTOS:");
        jLabelSala.setText("SALA:");
        int numeroAsientos=(int)jSpinnerNumeroAsientos.getValue();
        asientos=new int[numeroAsientos];
        sala=jComboBoxPelicula.getSelectedIndex()+1;
        int i=0, asientoMaximo=0, asientoMinimo=0;
        if(jCheckBoxPrimeraFila.isSelected()){
            asientoMaximo=10;
            asientoMinimo=1;
        }
        else{
            asientoMaximo=60;
            asientoMinimo=11;
        }
        do{
            int aleatorio=generarNumeroAleatorio(asientoMinimo, asientoMaximo);
            boolean ocupado=false;
            for(int j=0;j<asientos.length;j++){
                if(asientos[j]==aleatorio) ocupado=true;
            }
            if(!ocupado){
                asientos[i]=aleatorio;
                i++;
            }
        }while(i<numeroAsientos);
        for(int j=0;j<asientos.length;j++){
            jLabelAsientos.setText(jLabelAsientos.getText()+"  "+asientos[j]);
        }
        jLabelSala.setText(jLabelSala.getText()+" "+sala);
        jButtonConfirmarCompra.setEnabled(true);
        
    }//GEN-LAST:event_jButtonGenerarAsientosActionPerformed

    private void jButtonConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarCompraActionPerformed
        String mensaje="Compra de "+asientos.length+" asientos para ver "+peliculaActual.getTitulo()+".\nAsientos: "+Arrays.toString(asientos)+".\nSala "+sala;
        sound.play();
        JOptionPane.showMessageDialog(this,mensaje,"Compra realizada",JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
    }//GEN-LAST:event_jButtonConfirmarCompraActionPerformed

     private int generarNumeroAleatorio(int min, int max){
        Random random = new Random(); //Creamos un objeto de la clase random
        int number = random.nextInt((max-min) + 1) + min; //Generamos el número aleatorio
        return number; //Lo devolvemos
    }
     
    public void actualizarPeliculaActual(){
        jButtonConfirmarCompra.setEnabled(false);
        jLabelAsientos.setText("ASIENTOS:");
        jLabelSala.setText("SALA:");
        for(Pelicula p:peliculas){
            if(p.getTitulo().equals(jComboBoxPelicula.getSelectedItem())){
                peliculaActual=p;
                jLabelPrecio.setText("Precio: "+peliculaActual.getPrecio()*(int)jSpinnerNumeroAsientos.getValue()+"€");
            }
        }
        jLabelPeliculaActual.setIcon(new ImageIcon(getClass().getResource("/actividad4_1/imgs/"+peliculaActual.getTitulo()+".png")));
    }
    public void limpiarCampos(){
        jLabelAsientos.setText("ASIENTOS:");
        jLabelSala.setText("SALA:");
        jLabelPrecio.setText("Total: 0.0€");
        jComboBoxPelicula.setSelectedIndex(0);
        jSpinnerNumeroAsientos.setValue(1);
        jCheckBoxPrimeraFila.setSelected(false);
    }
    public void añadirListenersCartelera(){
        jLabelTitanic.addMouseListener(new MiMouseListener());
        jLabelMillionDollarBaby.addMouseListener(new MiMouseListener());
        jLabelTheBoogeyman.addMouseListener(new MiMouseListener());
        jLabelCastilloAmbulante.addMouseListener(new MiMouseListener());
        jLabelElPadrino.addMouseListener(new MiMouseListener());
        jLabelInsidious3.addMouseListener(new MiMouseListener());
        jLabelMinions.addMouseListener(new MiMouseListener());
        jLabelJurassicPark.addMouseListener(new MiMouseListener());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarCompra;
    private javax.swing.JButton jButtonGenerarAsientos;
    private javax.swing.JCheckBox jCheckBoxPrimeraFila;
    private javax.swing.JComboBox<String> jComboBoxPelicula;
    private javax.swing.JLabel jLabelAsientos;
    private javax.swing.JLabel jLabelCastilloAmbulante;
    private javax.swing.JLabel jLabelElPadrino;
    private javax.swing.JLabel jLabelInsidious3;
    private javax.swing.JLabel jLabelJurassicPark;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelLogo2;
    private javax.swing.JLabel jLabelMillionDollarBaby;
    private javax.swing.JLabel jLabelMinions;
    private javax.swing.JLabel jLabelNumeroAsientos;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelPeliculaActual;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelTheBoogeyman;
    private javax.swing.JLabel jLabelTitanic;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelComprarEntrada;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JPanel jPanelPeliculas;
    private javax.swing.JPanel jPanelVerCartelera;
    private javax.swing.JSpinner jSpinnerNumeroAsientos;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
