/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut6_actividad3.juego3;

/**
 *
 * @author Tarde
 */
public class JuegoMoverBola extends javax.swing.JFrame {

    /**
     * Creates new form JuegoMoverBola
     */
    public JuegoMoverBola() {
        initComponents();
        setTitle("Move a Ball");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelControles = new javax.swing.JPanel();
        jButtonUp = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        jButtonLeft = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();
        juegoPanel = new practica1ut6_actividad3.juego3.JuegoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelControles.setBackground(new java.awt.Color(255, 255, 255));
        jPanelControles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUp.setText("UP");
        jButtonUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonUpMouseReleased(evt);
            }
        });
        jPanelControles.add(jButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 40));

        jButtonDown.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDown.setText("DOWN");
        jButtonDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonDownMouseReleased(evt);
            }
        });
        jPanelControles.add(jButtonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 40));

        jButtonLeft.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLeft.setText("LEFT");
        jButtonLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonLeftMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonLeftMouseReleased(evt);
            }
        });
        jPanelControles.add(jButtonLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 90, 40));

        jButtonRight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRight.setText("RIGHT");
        jButtonRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonRightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonRightMouseReleased(evt);
            }
        });
        jPanelControles.add(jButtonRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 40));

        getContentPane().add(jPanelControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 200));

        juegoPanel.setPreferredSize(new java.awt.Dimension(400, 0));

        javax.swing.GroupLayout juegoPanelLayout = new javax.swing.GroupLayout(juegoPanel);
        juegoPanel.setLayout(juegoPanelLayout);
        juegoPanelLayout.setHorizontalGroup(
            juegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        juegoPanelLayout.setVerticalGroup(
            juegoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(juegoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpMousePressed
        juegoPanel.velY=-2;
    }//GEN-LAST:event_jButtonUpMousePressed

    private void jButtonUpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpMouseReleased
        juegoPanel.velY=0;
    }//GEN-LAST:event_jButtonUpMouseReleased

    private void jButtonDownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownMousePressed
        juegoPanel.velY=2;
    }//GEN-LAST:event_jButtonDownMousePressed

    private void jButtonDownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownMouseReleased
        juegoPanel.velY=0;
    }//GEN-LAST:event_jButtonDownMouseReleased

    private void jButtonLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLeftMousePressed
        juegoPanel.velX=-2;
    }//GEN-LAST:event_jButtonLeftMousePressed

    private void jButtonLeftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLeftMouseReleased
        juegoPanel.velX=0;
    }//GEN-LAST:event_jButtonLeftMouseReleased

    private void jButtonRightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRightMousePressed
        juegoPanel.velX=2;
    }//GEN-LAST:event_jButtonRightMousePressed

    private void jButtonRightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRightMouseReleased
        juegoPanel.velX=0;
    }//GEN-LAST:event_jButtonRightMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoMoverBola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonLeft;
    private javax.swing.JButton jButtonRight;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JPanel jPanelControles;
    private practica1ut6_actividad3.juego3.JuegoPanel juegoPanel;
    // End of variables declaration//GEN-END:variables
}
