/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut4.gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/practica1ut4/imgs/main_icon.png")).getImage());
        setLocationRelativeTo(null); //Para que aparezca en el centro de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanelSocio = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelNif = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNacionalidad = new javax.swing.JLabel();
        jLabelNoticias = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldNif = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxNacionalidad = new javax.swing.JComboBox<>();
        jPanelSocio1 = new javax.swing.JPanel();
        jCheckBoxAventura = new javax.swing.JCheckBox();
        jCheckBoxNegra = new javax.swing.JCheckBox();
        jCheckBoxFantastica = new javax.swing.JCheckBox();
        jCheckBoxHistorica = new javax.swing.JCheckBox();
        jCheckBoxCienciaFiccion = new javax.swing.JCheckBox();
        jCheckBoxJuvenil = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAñadir = new javax.swing.JMenuItem();
        jMenuItemVerTabla = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/foto.png"))); // NOI18N
        jPanelPrincipal.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 470));

        jPanelSocio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Socio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N

        jLabelNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelApellidos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelApellidos.setText("Apellidos:");

        jLabelNif.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNif.setText("NIF:");

        jLabelEmail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelEmail.setText("E-mail: ");

        jLabelNacionalidad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNacionalidad.setText("Nacionalidad:");

        jLabelNoticias.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNoticias.setText("Desea recibir noticias en su correo: ");

        buttonGroup1.add(jRadioButtonSi);
        jRadioButtonSi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioButtonSi.setText("Sí");

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioButtonNo.setText("No");

        jTextFieldNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldApellidos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldNif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jComboBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bélgica", "Brasil", "España", "Estados Unidos" }));
        jComboBoxNacionalidad.setSelectedIndex(2);

        javax.swing.GroupLayout jPanelSocioLayout = new javax.swing.GroupLayout(jPanelSocio);
        jPanelSocio.setLayout(jPanelSocioLayout);
        jPanelSocioLayout.setHorizontalGroup(
            jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSocioLayout.createSequentialGroup()
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSocioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelSocioLayout.createSequentialGroup()
                                .addComponent(jLabelNacionalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSocioLayout.createSequentialGroup()
                                .addComponent(jLabelNoticias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNo))
                            .addComponent(jLabelNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSocioLayout.createSequentialGroup()
                                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelApellidos)
                                    .addComponent(jLabelNif)
                                    .addComponent(jLabelEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))))
                    .addGroup(jPanelSocioLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelSocioLayout.setVerticalGroup(
            jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNif)
                    .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNacionalidad)
                    .addComponent(jComboBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoticias)
                    .addComponent(jRadioButtonSi)
                    .addComponent(jRadioButtonNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 390, 290));

        jPanelSocio1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Preferencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N

        jCheckBoxAventura.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxAventura.setText("Aventura");

        jCheckBoxNegra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxNegra.setText("Negra");

        jCheckBoxFantastica.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxFantastica.setText("Fantástica");

        jCheckBoxHistorica.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxHistorica.setText("Histórica");

        jCheckBoxCienciaFiccion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxCienciaFiccion.setText("Ciencia ficción");

        jCheckBoxJuvenil.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxJuvenil.setText("Juvenil");

        javax.swing.GroupLayout jPanelSocio1Layout = new javax.swing.GroupLayout(jPanelSocio1);
        jPanelSocio1.setLayout(jPanelSocio1Layout);
        jPanelSocio1Layout.setHorizontalGroup(
            jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSocio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAventura)
                    .addComponent(jCheckBoxNegra))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxFantastica)
                    .addComponent(jCheckBoxHistorica))
                .addGap(18, 18, 18)
                .addGroup(jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxJuvenil)
                    .addComponent(jCheckBoxCienciaFiccion))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelSocio1Layout.setVerticalGroup(
            jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSocio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAventura)
                    .addComponent(jCheckBoxFantastica)
                    .addComponent(jCheckBoxCienciaFiccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSocio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNegra)
                    .addComponent(jCheckBoxHistorica)
                    .addComponent(jCheckBoxJuvenil))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelSocio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 390, 120));

        jMenuArchivo.setText("Archivo");

        jMenuItemAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/nuevo.png"))); // NOI18N
        jMenuItemAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAñadir);

        jMenuItemVerTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/guardar.png"))); // NOI18N
        jMenuArchivo.add(jMenuItemVerTabla);

        jMenuBar1.add(jMenuArchivo);

        jMenuAyuda.setText("Ayuda");
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirActionPerformed
        boolean registrar=true;
        String nombre=jTextFieldNombre.getText();
        String apellidos=jTextFieldApellidos.getText();
        String nif=jTextFieldNif.getText();
        String email=jTextFieldEmail.getText();
        String nacionalidad=jComboBoxNacionalidad.getSelectedItem().toString();
        String mensaje="";
        if(containsNumber(nombre)){
            registrar=false;
            mensaje+="El nombre no puede contener letras\n";
        }
        if(containsNumber(apellidos)){
            registrar=false;
            mensaje+="Los apellidos no pueden contener letras\n";
        }
        if(!isValidDni(nif)){
            registrar=false;
            mensaje+="El DNI no es válido\n";
        }
        if(nombre.equals("") || apellidos.equals("") || nif.equals("") || email.equals("")){
            registrar=false;
            mensaje+="Todos los campos deben ser rellenados\n";
        }
        if(registrar){
            mensaje="Usuario "+nombre+" "+apellidos+" registrado, con DNI "+nif+" y correo "+email+".\nNacionalidad: "+nacionalidad+". ";
            if(jRadioButtonSi.isSelected())mensaje+="Se ha suscrito a las ultimas novedades";
            JOptionPane.showMessageDialog(this,mensaje, "Usuario registrado",JOptionPane.INFORMATION_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this,mensaje, "Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItemAñadirActionPerformed

    public boolean containsNumber(String s){
        return s.matches("[0-9]+");
    }
    public boolean isValidDni(String s){
        return s.matches("[0-9]{8}[A-Z]{1}");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxAventura;
    private javax.swing.JCheckBox jCheckBoxCienciaFiccion;
    private javax.swing.JCheckBox jCheckBoxFantastica;
    private javax.swing.JCheckBox jCheckBoxHistorica;
    private javax.swing.JCheckBox jCheckBoxJuvenil;
    private javax.swing.JCheckBox jCheckBoxNegra;
    private javax.swing.JComboBox<String> jComboBoxNacionalidad;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNif;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNoticias;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAñadir;
    private javax.swing.JMenuItem jMenuItemVerTabla;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSocio;
    private javax.swing.JPanel jPanelSocio1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonSi;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNif;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
