/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut4.gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/practica1ut4/imgs/main_icon.png")).getImage());
        setLocationRelativeTo(null); //Para que aparezca en el centro de la pantalla
        jRadioButtonSi.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanelSocio = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelNif = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNacionalidad = new javax.swing.JLabel();
        jLabelNoticias = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldNif = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxNacionalidad = new javax.swing.JComboBox<>();
        jLabelBandera = new javax.swing.JLabel();
        jPanelSocio1 = new javax.swing.JPanel();
        jCheckBoxAventura = new javax.swing.JCheckBox();
        jCheckBoxNegra = new javax.swing.JCheckBox();
        jCheckBoxFantastica = new javax.swing.JCheckBox();
        jCheckBoxHistorica = new javax.swing.JCheckBox();
        jCheckBoxCienciaFiccion = new javax.swing.JCheckBox();
        jCheckBoxJuvenil = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAñadir = new javax.swing.JMenuItem();
        jMenuItemVerTabla = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/foto.png"))); // NOI18N
        jPanelPrincipal.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 470));

        jPanelSocio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Socio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N
        jPanelSocio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jPanelSocio.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 39, -1, -1));

        jLabelApellidos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelApellidos.setText("Apellidos:");
        jPanelSocio.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 81, -1, -1));

        jLabelNif.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNif.setText("NIF:");
        jPanelSocio.add(jLabelNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 123, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelEmail.setText("E-mail: ");
        jPanelSocio.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 165, -1, -1));

        jLabelNacionalidad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNacionalidad.setText("Nacionalidad:");
        jPanelSocio.add(jLabelNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 204, -1, -1));

        jLabelNoticias.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNoticias.setText("Desea recibir noticias en su correo: ");
        jPanelSocio.add(jLabelNoticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 247, -1, -1));

        buttonGroup1.add(jRadioButtonSi);
        jRadioButtonSi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioButtonSi.setText("Sí");
        jPanelSocio.add(jRadioButtonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 243, -1, -1));

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioButtonNo.setText("No");
        jPanelSocio.add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 243, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanelSocio.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 36, 246, -1));

        jTextFieldApellidos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanelSocio.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 78, 246, -1));

        jTextFieldNif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanelSocio.add(jTextFieldNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 120, 246, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanelSocio.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 162, 246, -1));

        jComboBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bélgica", "Brasil", "España", "Estados Unidos" }));
        jComboBoxNacionalidad.setSelectedIndex(2);
        jComboBoxNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNacionalidadActionPerformed(evt);
            }
        });
        jPanelSocio.add(jComboBoxNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 205, -1, -1));

        jLabelBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/España.png"))); // NOI18N
        jPanelSocio.add(jLabelBandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 208, 40, 20));

        jPanelPrincipal.add(jPanelSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 390, 290));

        jPanelSocio1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Preferencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N
        jPanelSocio1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxAventura.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxAventura.setText("Aventura");
        jPanelSocio1.add(jCheckBoxAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 32, -1, -1));

        jCheckBoxNegra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxNegra.setText("Negra");
        jPanelSocio1.add(jCheckBoxNegra, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, -1));

        jCheckBoxFantastica.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxFantastica.setText("Fantástica");
        jPanelSocio1.add(jCheckBoxFantastica, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 32, -1, -1));

        jCheckBoxHistorica.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxHistorica.setText("Histórica");
        jPanelSocio1.add(jCheckBoxHistorica, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 62, -1, -1));

        jCheckBoxCienciaFiccion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxCienciaFiccion.setText("Ciencia ficción");
        jPanelSocio1.add(jCheckBoxCienciaFiccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 32, -1, -1));

        jCheckBoxJuvenil.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCheckBoxJuvenil.setText("Juvenil");
        jPanelSocio1.add(jCheckBoxJuvenil, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 62, -1, -1));

        jPanelPrincipal.add(jPanelSocio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 390, 120));

        jMenuArchivo.setText("Archivo");

        jMenuItemAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/nuevo.png"))); // NOI18N
        jMenuItemAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAñadir);

        jMenuItemVerTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1ut4/imgs/guardar.png"))); // NOI18N
        jMenuArchivo.add(jMenuItemVerTabla);

        jMenuBar1.add(jMenuArchivo);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAyudaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirActionPerformed
        boolean registrar=true;
        String nombre=jTextFieldNombre.getText();
        String apellidos=jTextFieldApellidos.getText();
        String nif=jTextFieldNif.getText();
        String email=jTextFieldEmail.getText();
        String nacionalidad=jComboBoxNacionalidad.getSelectedItem().toString();
        String mensaje="";
        if(nombre.equals("") || apellidos.equals("") || nif.equals("") || email.equals("")){
            registrar=false;
            mensaje+="Todos los campos deben ser rellenados\n";
        }
        else{
            if(containsNumber(nombre)){
                registrar=false;
                mensaje+="El nombre no puede contener numeros\n";
            }
            if(containsNumber(apellidos)){
                registrar=false;
                mensaje+="Los apellidos no pueden contener numeros\n";
            }
            if(!isValidDni(nif)){
                registrar=false;
                mensaje+="El DNI no es válido\n";
            }
        }
        
        if(registrar){
            mensaje="Usuario "+nombre+" "+apellidos+" registrado, con DNI "+nif+" y correo "+email+".\nNacionalidad: "+nacionalidad+". ";
            if(jRadioButtonSi.isSelected())mensaje+="Se ha suscrito a las ultimas novedades";
            JOptionPane.showMessageDialog(this,mensaje, "Usuario registrado",JOptionPane.INFORMATION_MESSAGE);
            vaciarCampos();//Vaciamos los campos
            
        }
        else JOptionPane.showMessageDialog(this,mensaje, "Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItemAñadirActionPerformed

    private void jComboBoxNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNacionalidadActionPerformed
        jLabelBandera.setIcon(new ImageIcon(getClass().getResource("/practica1ut4/imgs/"+jComboBoxNacionalidad.getSelectedItem()+".png")));
    }//GEN-LAST:event_jComboBoxNacionalidadActionPerformed

    private void jMenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaActionPerformed
        JOptionPane.showMessageDialog(this,"Pulse Archivo para desplegar las opciones. Pulse el primer icono para añadir un usuario\nPulse el segundo icono para ver la tabla de socios","Ayuda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuAyudaActionPerformed

    public boolean containsNumber(String s){
        return s.matches(".*\\d+.*");
    }
    public boolean isValidDni(String s){
        return s.matches("[0-9]{8}[A-Z]{1}");
    }
    public void vaciarCampos(){
        jTextFieldNombre.setText("");
            jTextFieldApellidos.setText("");
            jTextFieldNif.setText("");
            jTextFieldEmail.setText("");
            jComboBoxNacionalidad.setSelectedIndex(3);
            jRadioButtonSi.setSelected(true);
            jCheckBoxAventura.setSelected(false);
            jCheckBoxCienciaFiccion.setSelected(false);
            jCheckBoxFantastica.setSelected(false);
            jCheckBoxHistorica.setSelected(false);
            jCheckBoxJuvenil.setSelected(false);
            jCheckBoxNegra.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxAventura;
    private javax.swing.JCheckBox jCheckBoxCienciaFiccion;
    private javax.swing.JCheckBox jCheckBoxFantastica;
    private javax.swing.JCheckBox jCheckBoxHistorica;
    private javax.swing.JCheckBox jCheckBoxJuvenil;
    private javax.swing.JCheckBox jCheckBoxNegra;
    private javax.swing.JComboBox<String> jComboBoxNacionalidad;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelBandera;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNif;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNoticias;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAñadir;
    private javax.swing.JMenuItem jMenuItemVerTabla;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSocio;
    private javax.swing.JPanel jPanelSocio1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonSi;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNif;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
