/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut4.gui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import practica1ut4.logica.ListaSocios;
import practica1ut4.logica.Socio;

/**
 *
 * @author Tarde
 */
public class TablaSocios extends javax.swing.JDialog {

    /**
     * Creates new form TablaSocios
     */
    public TablaSocios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setIconImage(new ImageIcon(getClass().getResource("/practica1ut4/imgs/main_icon.png")).getImage()); //Icono de la ventana
        setLocationRelativeTo(null); //Para que aparezca en el centro de la pantalla
        initComponents();
        refrescarTabla();
    }

    private void refrescarTabla(){
        DefaultTableModel dtm=new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //Hacemos que las celdas no sean editables al hacer doble clic sobre ellas
        }
        };
        dtm.setColumnIdentifiers(new String[]{"Nombre","Apellidos","NIF","Email","Nacionalidad","Notificaciones?","Preferencias"}); //Ponemos nombre a la columna
        for(Socio s:ListaSocios.getListaSocios()){ //Para cada compra de la lista
            String[]fila=new String[7]; //Creamos un Array de Strings de longitud 5
            fila[0]=s.getNombre();
            fila[1]=s.getApellidos();
            fila[2]=s.getNif();
            fila[3]=s.getEmail();
            fila[4]=s.getNacionalidad();
            if(s.isNotificaciones()) fila[5]="Sí";
            else fila[5]="No";
            fila[6]=""; //Al principio tiene un null, asi se evita
            for(String preferencia:s.getPreferencias()){
                fila[6]+=preferencia+" ";
            }
            System.out.println(Arrays.toString(fila));
            dtm.addRow(fila); //Añadimos el array a la tabla
        }
        jTableSocios.setModel(dtm); //Establecemos el modelo creado como el de la tabla
        
        jScrollPane1.getViewport().setBackground(new Color(0xFFFFFF)); //Establecemos el color de fondo del jScrollPane que contiene la tabla
        
        //Apartado visual de la tabla
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.BLACK); //Cambiamos el fondo del header
        headerRenderer.setForeground(Color.WHITE); //Cambiamos el color de fuente del header
        headerRenderer.setHorizontalAlignment(JLabel.CENTER); //Centramos el texto del header
        for (int i = 0; i < jTableSocios.getModel().getColumnCount(); i++) { //Para cada columna
            jTableSocios.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer); //Establecemos el header al que hemos creado
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "NIF", "Email", "Nacionalidad", "Notificaciones?", "Preferencias"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        jPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 300));

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TablaSocios dialog = new TablaSocios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSocios;
    // End of variables declaration//GEN-END:variables
}
