/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoCine.gui;

import proyectoCine.beans.Cine;
import proyectoCine.beans.Genero;
import proyectoCine.beans.Pelicula;
import proyectoCine.dao.CineDao;
import proyectoCine.dao.GeneroDao;
import proyectoCine.dao.PeliculaDao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRCsvExporter;
import net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter;
import net.sf.jasperreports.export.SimpleCsvExporterConfiguration;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.export.SimpleWriterExporterOutput;
import net.sf.jasperreports.export.SimpleXlsxReportConfiguration;

/**
 * @author Fatima Mortahil Chachou
 * @author Daniel Monforte Ibias
 * @author Victoria del Pino De Paz
 * 
 */
public class Principal extends javax.swing.JFrame {

    private String filtroGenero = "Todos", filtroCine = "Todos";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/cine2.png")).getImage());
        this.setLocationRelativeTo(null);
        refrescarTablaPeliculas(PeliculaDao.listarPeliculas());
        //Rellenamos todos los ComboBox con los datos de la base de datos
        rellenarComboBoxCine();
        rellenarComboBoxGenero();
        rellenarComboBoxPeliculas();
    }

    private void refrescarTablaPeliculas(List<Pelicula> listaPeliculas) {
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //Hacemos que las celdas no sean editables al hacer doble clic sobre ellas
            }
        };
        dtm.setColumnIdentifiers(new String[]{"Titulo", "Genero", "Vista", "Cine", "Calificacion"}); //Ponemos nombre a la columna
        for (Pelicula p : listaPeliculas) { //Para cada pelicula de la lista
            String[] fila = new String[5]; //Creamos un Array de Strings de longitud 5
            fila[0] = p.getNombrePelicula();
            fila[1] = p.getGenero().getNombreGenero();
            if (p.isVisto()) {
                fila[2] = "Si";
            } else {
                fila[2] = "No";
            }
            fila[3] = p.getCine().getNombreCine();
            fila[4] = p.getCalificacion() + "";
            dtm.addRow(fila); //Añadimos el array a la tabla
        }
        jTablePeliculas.setModel(dtm); //Establecemos el modelo creado como el de la tabla
        
        jScrollPane1.getViewport().setBackground(new Color(0xFDF5E8)); //Establecemos el color de fondo del jScrollPane que contiene la tabla

        //Apartado visual de la tabla
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(0xC8B18B)); //Cambiamos el fondo del header
        headerRenderer.setForeground(Color.BLACK); //Cambiamos el color de fuente del header
        headerRenderer.setHorizontalAlignment(JLabel.CENTER); //Centramos el texto del header
        for (int i = 0; i < jTablePeliculas.getModel().getColumnCount(); i++) { //Para cada columna
            jTablePeliculas.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer); //Establecemos el header al que hemos creado
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVista = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTablaPeliculas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeliculas = new javax.swing.JTable();
        jLabelFiltroGenero = new javax.swing.JLabel();
        jLabelFiltroCine = new javax.swing.JLabel();
        jComboBoxGenerosFiltro = new javax.swing.JComboBox<>();
        jComboBoxCinesFiltro = new javax.swing.JComboBox<>();
        jButtonFiltrar = new javax.swing.JButton();
        jPanelAñadirCine = new javax.swing.JPanel();
        jPanelTituloCine = new javax.swing.JPanel();
        jLabelNuevoCine = new javax.swing.JLabel();
        jLabelIcon1 = new javax.swing.JLabel();
        jLabelIcon2 = new javax.swing.JLabel();
        jPanelCamposCine = new javax.swing.JPanel();
        jLabelNombreCine = new javax.swing.JLabel();
        jTextFieldNombreCine = new javax.swing.JTextField();
        jLabelDireccionCine = new javax.swing.JLabel();
        jTextFieldDireccionCine = new javax.swing.JTextField();
        jButtonGuardarCine = new javax.swing.JButton();
        jPanelAñadirPelicula = new javax.swing.JPanel();
        jPanelTituloPelicula = new javax.swing.JPanel();
        jLabelNuevaPelicula = new javax.swing.JLabel();
        jLabelIcon3 = new javax.swing.JLabel();
        jLabelIcon4 = new javax.swing.JLabel();
        jButtonGuardarPelicula = new javax.swing.JButton();
        jPanelCamposPelicula = new javax.swing.JPanel();
        jLabelTituloPelicula = new javax.swing.JLabel();
        jTextFieldTituloPelicula = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jComboBoxGeneros = new javax.swing.JComboBox<>();
        jLabelVista = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jLabelCine = new javax.swing.JLabel();
        jComboBoxCines = new javax.swing.JComboBox<>();
        jLabelCal = new javax.swing.JLabel();
        jTextFieldCal = new javax.swing.JTextField();
        jPanelModificarPelicula = new javax.swing.JPanel();
        jPanelTituloPelicula1 = new javax.swing.JPanel();
        jLabelNuevaPelicula1 = new javax.swing.JLabel();
        jLabelIcon5 = new javax.swing.JLabel();
        jLabelIcon6 = new javax.swing.JLabel();
        jPanelCamposModificarPelicula = new javax.swing.JPanel();
        jLabelTituloPelicula1 = new javax.swing.JLabel();
        jLabelGenero1 = new javax.swing.JLabel();
        jComboBoxTitulo = new javax.swing.JComboBox<>();
        jComboBoxGeneros1 = new javax.swing.JComboBox<>();
        jLabelVista1 = new javax.swing.JLabel();
        jRadioButtonSi1 = new javax.swing.JRadioButton();
        jRadioButtonNo1 = new javax.swing.JRadioButton();
        jLabelCine1 = new javax.swing.JLabel();
        jComboBoxCines1 = new javax.swing.JComboBox<>();
        jLabelCal1 = new javax.swing.JLabel();
        jTextFieldCal1 = new javax.swing.JTextField();
        jButtonModificarPelicula = new javax.swing.JButton();
        jButtonEliminarPelicula = new javax.swing.JButton();
        jPanelSacarInforme = new javax.swing.JPanel();
        jButtonImprimirInforme = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxFormatos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        jPanelTablaPeliculas.setBackground(new java.awt.Color(253, 245, 232));
        jPanelTablaPeliculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePeliculas);

        jPanelTablaPeliculas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 342));

        jLabelFiltroGenero.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelFiltroGenero.setText("Filtrar por genero:");
        jPanelTablaPeliculas.add(jLabelFiltroGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabelFiltroCine.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabelFiltroCine.setText("Filtrar por cine:");
        jPanelTablaPeliculas.add(jLabelFiltroCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jComboBoxGenerosFiltro.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxGenerosFiltro.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelTablaPeliculas.add(jComboBoxGenerosFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 340, 30));

        jComboBoxCinesFiltro.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxCinesFiltro.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelTablaPeliculas.add(jComboBoxCinesFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 340, 30));

        jButtonFiltrar.setBackground(new java.awt.Color(200, 177, 139));
        jButtonFiltrar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });
        jPanelTablaPeliculas.add(jButtonFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 223, 50));

        jTabbedPane1.addTab("Tabla de Películas", jPanelTablaPeliculas);

        jPanelAñadirCine.setBackground(new java.awt.Color(253, 245, 232));
        jPanelAñadirCine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTituloCine.setOpaque(false);
        jPanelTituloCine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNuevoCine.setFont(new java.awt.Font("Candara", 1, 56)); // NOI18N
        jLabelNuevoCine.setText("Nuevo Cine");
        jPanelTituloCine.add(jLabelNuevoCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabelIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cine2.png"))); // NOI18N
        jPanelTituloCine.add(jLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabelIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cine2.png"))); // NOI18N
        jPanelTituloCine.add(jLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanelAñadirCine.add(jPanelTituloCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        jPanelCamposCine.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 177, 139), 3), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 18))); // NOI18N
        jPanelCamposCine.setOpaque(false);
        jPanelCamposCine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreCine.setFont(new java.awt.Font("Candara", 0, 28)); // NOI18N
        jLabelNombreCine.setText("Nombre del Cine:");
        jPanelCamposCine.add(jLabelNombreCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldNombreCine.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposCine.add(jTextFieldNombreCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 360, -1));

        jLabelDireccionCine.setFont(new java.awt.Font("Candara", 0, 28)); // NOI18N
        jLabelDireccionCine.setText("Dirección del cine:");
        jPanelCamposCine.add(jLabelDireccionCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTextFieldDireccionCine.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposCine.add(jTextFieldDireccionCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 360, -1));

        jPanelAñadirCine.add(jPanelCamposCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 640, 220));

        jButtonGuardarCine.setBackground(new java.awt.Color(200, 177, 139));
        jButtonGuardarCine.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonGuardarCine.setText("Guardar Cine");
        jButtonGuardarCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCineActionPerformed(evt);
            }
        });
        jPanelAñadirCine.add(jButtonGuardarCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 399, 223, 50));

        jTabbedPane1.addTab("Añadir Cine", jPanelAñadirCine);

        jPanelAñadirPelicula.setBackground(new java.awt.Color(253, 245, 232));
        jPanelAñadirPelicula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTituloPelicula.setOpaque(false);
        jPanelTituloPelicula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNuevaPelicula.setFont(new java.awt.Font("Candara", 1, 56)); // NOI18N
        jLabelNuevaPelicula.setText("Nueva Película");
        jPanelTituloPelicula.add(jLabelNuevaPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabelIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cine5.png"))); // NOI18N
        jPanelTituloPelicula.add(jLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabelIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cine5.png"))); // NOI18N
        jPanelTituloPelicula.add(jLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanelAñadirPelicula.add(jPanelTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jButtonGuardarPelicula.setBackground(new java.awt.Color(200, 177, 139));
        jButtonGuardarPelicula.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonGuardarPelicula.setText("Guardar Película");
        jButtonGuardarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPeliculaActionPerformed(evt);
            }
        });
        jPanelAñadirPelicula.add(jButtonGuardarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 220, -1));

        jPanelCamposPelicula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 177, 139), 3), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 18))); // NOI18N
        jPanelCamposPelicula.setOpaque(false);
        jPanelCamposPelicula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloPelicula.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelTituloPelicula.setText("Título:");
        jPanelCamposPelicula.add(jLabelTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTextFieldTituloPelicula.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposPelicula.add(jTextFieldTituloPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 430, -1));

        jLabelGenero.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelGenero.setText("Genero :");
        jPanelCamposPelicula.add(jLabelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jComboBoxGeneros.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxGeneros.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposPelicula.add(jComboBoxGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 430, -1));

        jLabelVista.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelVista.setText("Vista:");
        jPanelCamposPelicula.add(jLabelVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        grupoVista.add(jRadioButtonSi);
        jRadioButtonSi.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jRadioButtonSi.setText("Si");
        jRadioButtonSi.setOpaque(false);
        jPanelCamposPelicula.add(jRadioButtonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        grupoVista.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jRadioButtonNo.setText("No");
        jRadioButtonNo.setOpaque(false);
        jPanelCamposPelicula.add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabelCine.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelCine.setText("Cine:");
        jPanelCamposPelicula.add(jLabelCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jComboBoxCines.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxCines.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposPelicula.add(jComboBoxCines, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 430, -1));

        jLabelCal.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelCal.setText("Calificación: ");
        jPanelCamposPelicula.add(jLabelCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanelCamposPelicula.add(jTextFieldCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 430, 34));

        jPanelAñadirPelicula.add(jPanelCamposPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 680, 320));

        jTabbedPane1.addTab("Añadir Película", jPanelAñadirPelicula);

        jPanelModificarPelicula.setBackground(new java.awt.Color(253, 245, 232));
        jPanelModificarPelicula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTituloPelicula1.setOpaque(false);
        jPanelTituloPelicula1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNuevaPelicula1.setFont(new java.awt.Font("Candara", 1, 56)); // NOI18N
        jLabelNuevaPelicula1.setText("Modificar Película");
        jPanelTituloPelicula1.add(jLabelNuevaPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabelIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cine5.png"))); // NOI18N
        jPanelTituloPelicula1.add(jLabelIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabelIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cine5.png"))); // NOI18N
        jPanelTituloPelicula1.add(jLabelIcon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanelModificarPelicula.add(jPanelTituloPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanelCamposModificarPelicula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 177, 139), 3), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 18))); // NOI18N
        jPanelCamposModificarPelicula.setOpaque(false);
        jPanelCamposModificarPelicula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloPelicula1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelTituloPelicula1.setText("Título:");
        jPanelCamposModificarPelicula.add(jLabelTituloPelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelGenero1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelGenero1.setText("Genero :");
        jPanelCamposModificarPelicula.add(jLabelGenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jComboBoxTitulo.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxTitulo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jComboBoxTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTituloActionPerformed(evt);
            }
        });
        jPanelCamposModificarPelicula.add(jComboBoxTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 430, -1));

        jComboBoxGeneros1.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxGeneros1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposModificarPelicula.add(jComboBoxGeneros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 430, -1));

        jLabelVista1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelVista1.setText("Vista:");
        jPanelCamposModificarPelicula.add(jLabelVista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        grupoVista.add(jRadioButtonSi1);
        jRadioButtonSi1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jRadioButtonSi1.setText("Si");
        jRadioButtonSi1.setOpaque(false);
        jPanelCamposModificarPelicula.add(jRadioButtonSi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        grupoVista.add(jRadioButtonNo1);
        jRadioButtonNo1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jRadioButtonNo1.setText("No");
        jRadioButtonNo1.setOpaque(false);
        jPanelCamposModificarPelicula.add(jRadioButtonNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabelCine1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelCine1.setText("Cine:");
        jPanelCamposModificarPelicula.add(jLabelCine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jComboBoxCines1.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxCines1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelCamposModificarPelicula.add(jComboBoxCines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 430, -1));

        jLabelCal1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelCal1.setText("Calificación: ");
        jPanelCamposModificarPelicula.add(jLabelCal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanelCamposModificarPelicula.add(jTextFieldCal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 430, 34));

        jPanelModificarPelicula.add(jPanelCamposModificarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 680, 320));

        jButtonModificarPelicula.setBackground(new java.awt.Color(200, 177, 139));
        jButtonModificarPelicula.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonModificarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/modificar.png"))); // NOI18N
        jButtonModificarPelicula.setText("Modificar Película");
        jButtonModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPeliculaActionPerformed(evt);
            }
        });
        jPanelModificarPelicula.add(jButtonModificarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 250, -1));

        jButtonEliminarPelicula.setBackground(new java.awt.Color(200, 177, 139));
        jButtonEliminarPelicula.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonEliminarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cruz.png"))); // NOI18N
        jButtonEliminarPelicula.setText("Eliminar Película");
        jButtonEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPeliculaActionPerformed(evt);
            }
        });
        jPanelModificarPelicula.add(jButtonEliminarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 260, -1));

        jTabbedPane1.addTab("Modificar Película", jPanelModificarPelicula);

        jPanelSacarInforme.setBackground(new java.awt.Color(253, 245, 232));
        jPanelSacarInforme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonImprimirInforme.setBackground(new java.awt.Color(200, 177, 139));
        jButtonImprimirInforme.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButtonImprimirInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/informe.png"))); // NOI18N
        jButtonImprimirInforme.setText("Imprimir Informe");
        jButtonImprimirInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirInformeActionPerformed(evt);
            }
        });
        jPanelSacarInforme.add(jButtonImprimirInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 290, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/informEjemplo.png"))); // NOI18N
        jPanelSacarInforme.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jComboBoxFormatos.setBackground(new java.awt.Color(200, 177, 139));
        jComboBoxFormatos.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jComboBoxFormatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "CSV", "XLSX", "XML" }));
        jPanelSacarInforme.add(jComboBoxFormatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, -1));

        jTabbedPane1.addTab("Sacar informe", jPanelSacarInforme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirInformeActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/peliculas", "root", ""); //Obtenemos conexion a la base de datos
            JasperPrint print = JasperFillManager.fillReport("reports/report_cines.jasper", null, connection);

            String formato = jComboBoxFormatos.getSelectedItem().toString().toLowerCase(); //Obtenemos el formato deseado
            String outputPath = "reports/informeCines." + formato;
            //Segun el formato generaremos un informe u otro de diferentes maneras
            switch (formato) {
                case "pdf":
                JasperExportManager.exportReportToPdfFile(print, outputPath);
                break;

                case "csv":
                SimpleCsvExporterConfiguration csvConfig = new SimpleCsvExporterConfiguration();
                csvConfig.setFieldDelimiter(";");
                new JRCsvExporter() {
                    {
                        setExporterInput(new SimpleExporterInput(print));
                        setExporterOutput(new SimpleWriterExporterOutput(outputPath));
                        setConfiguration(csvConfig);
                        exportReport();
                    }
                };
                break;

                case "xlsx":
                SimpleXlsxReportConfiguration xlsxConfig = new SimpleXlsxReportConfiguration();
                xlsxConfig.setDetectCellType(true);
                xlsxConfig.setOnePagePerSheet(false);
                new JRXlsxExporter() {
                    {
                        setExporterInput(new SimpleExporterInput(print));
                        setExporterOutput(new SimpleOutputStreamExporterOutput(outputPath));
                        setConfiguration(xlsxConfig);
                        exportReport();
                    }
                };
                break;
                case "xml":
                    JasperExportManager.exportReportToXmlFile(print, outputPath, true);
                    break;
            }
            JOptionPane.showMessageDialog(this, "Informe generado en la carpeta reports: " + outputPath, "AVISO", JOptionPane.INFORMATION_MESSAGE); //Avisamos al usuario para que sepa que se genero
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el informe: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); //Avisamos al usuario del error
        }
    }//GEN-LAST:event_jButtonImprimirInformeActionPerformed

    private void jButtonEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPeliculaActionPerformed
        Pelicula p = PeliculaDao.obtenerPeliculaPorTitulo(jComboBoxTitulo.getSelectedItem().toString()); //Obtenemos la pelicula seleccionada
        int confirm = JOptionPane.showConfirmDialog(this, "¿Desea eliminar la película " + p.getNombrePelicula() + "?", "Confirmación", JOptionPane.YES_NO_OPTION); //Damos al usuario la oportunidad de decidir si borrarla o no
        if (confirm == JOptionPane.YES_OPTION) { //Si decide que si
            PeliculaDao.eliminarPelicula(p.getNombrePelicula()); //La eliminamos
            refrescarTablaPeliculas(PeliculaDao.filtrarPeliculas(filtroGenero, filtroCine)); //Refrescamos la tabla para quitarla
            jComboBoxTitulo.removeItem(p.getNombrePelicula()); //La quitamos del comboBox de peliculas
            JOptionPane.showMessageDialog(this, p.getNombrePelicula()+" eliminada", "Eliminada", JOptionPane.INFORMATION_MESSAGE); //Informamos al usuario
        }
    }//GEN-LAST:event_jButtonEliminarPeliculaActionPerformed

    private void jButtonModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPeliculaActionPerformed
        Pelicula pelicula = PeliculaDao.obtenerPeliculaPorTitulo(jComboBoxTitulo.getSelectedItem().toString()); //Obtenemos la pelicula seleccionada
        if (pelicula != null) {
            //Obtenemos los datos ingresados
            Genero genero=GeneroDao.obtenerGeneroPorNombre(jComboBoxGeneros1.getSelectedItem().toString());
            boolean vista=false;
            if(jRadioButtonSi1.isSelected())vista=true;
            else if(jRadioButtonNo1.isSelected())vista=false;
            Cine cine=CineDao.obtenerCinePorNombre(jComboBoxCines1.getSelectedItem().toString());
            String calificacionText = jTextFieldCal1.getText().trim();
            int calificacion=0;
            if(vista){
                if (calificacionText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una calificación si ha visto la película", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                calificacion = Integer.parseInt(calificacionText);
                if (calificacion < 1 || calificacion > 5) {
                    JOptionPane.showMessageDialog(this, "La calificación debe estar entre 1 y 5", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La calificación debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            }
            PeliculaDao.modificarPelicula(new Pelicula(pelicula.getNombrePelicula(),genero,vista,cine,calificacion)); //Modificamos la pelicula con los nuevos datos
            JOptionPane.showMessageDialog(this, pelicula.getNombrePelicula()+" modificada", "Modificada", JOptionPane.INFORMATION_MESSAGE); //Avisamos al usuario
            refrescarTablaPeliculas(PeliculaDao.filtrarPeliculas(filtroGenero, filtroCine)); //Refrescamos la tabla para que salga con los cambios
        }
    }//GEN-LAST:event_jButtonModificarPeliculaActionPerformed

    private void jComboBoxTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTituloActionPerformed
        Pelicula p = PeliculaDao.obtenerPeliculaPorTitulo(jComboBoxTitulo.getSelectedItem().toString()); //Obtenemos la pelicula elegida
        //Hacemos que en los campos se ponga la informacion de la pelicula
        jComboBoxCines1.setSelectedItem(p.getCine().getNombreCine());
        jComboBoxGeneros1.setSelectedItem(p.getGenero().getNombreGenero());
        if (p.isVisto()) {
            jRadioButtonSi1.setSelected(true);
        } else {
            jRadioButtonNo1.setSelected(true);
        }
        jTextFieldCal1.setText(p.getCalificacion() + "");
    }//GEN-LAST:event_jComboBoxTituloActionPerformed

    private void jButtonGuardarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPeliculaActionPerformed
        String tituloPelicula = jTextFieldTituloPelicula.getText().trim(); //Obtenemos el titulo
        if (tituloPelicula.isEmpty()) { //Si esta vacio,  daremos un error
            JOptionPane.showMessageDialog(this, "El título no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(PeliculaDao.obtenerPeliculaPorTitulo(tituloPelicula)!=null){ //Si ya existe una peli con ese nombre,  daremos un error
            JOptionPane.showMessageDialog(this, "Ya existe una pelicula con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!jRadioButtonSi.isSelected() && !jRadioButtonNo.isSelected()) { //Si no esta seleccionado si se ha visto o no,  daremos un error
            JOptionPane.showMessageDialog(this, "Debe seleccionar si la ha visto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Obtenemos genero y cine
        String nombreGenero = (String) jComboBoxGeneros.getSelectedItem();
        String nombreCine = (String) jComboBoxCines.getSelectedItem();
        //Si alguno no está seleccionado, daremos error
        if (nombreGenero == null || nombreCine == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un género y un cine", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validamos el  campo de calificación si selecciona que la ha visto tiene que calificarla si o si
        boolean visto = jRadioButtonSi.isSelected();
        int calificacion = 0;
        if (visto) {
            String calificacionText = jTextFieldCal.getText().trim();
            if (calificacionText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una calificación si ha visto la película", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                calificacion = Integer.parseInt(calificacionText); //Vemios si es un numero valido
                if (calificacion < 1 || calificacion > 5) { //Ademas vemos que este entre 1 y 5
                    JOptionPane.showMessageDialog(this, "La calificación debe estar entre 1 y 5", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La calificación debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        //Obtenemos el genero y cine por sus nombres
        Genero genero = GeneroDao.obtenerGeneroPorNombre(nombreGenero);
        Cine cine = CineDao.obtenerCinePorNombre(nombreCine);
        Pelicula pelicula = new Pelicula(tituloPelicula, genero, visto, cine, calificacion); //Creamos la pelicula
        PeliculaDao.registrarPelicula(pelicula); //La registramos en la base de datos
        refrescarTablaPeliculas(PeliculaDao.filtrarPeliculas(filtroGenero, filtroCine)); //Refrescamos la tabla para que salga
        jComboBoxTitulo.addItem(pelicula.getNombrePelicula()); //Añadimos su titulo al comboBox de peliculas
        JOptionPane.showMessageDialog(this, "Película guardada", "Mensaje", JOptionPane.INFORMATION_MESSAGE); //Avisamos al usuario
        //Vaciamos los campos
        jTextFieldTituloPelicula.setText("");
        jComboBoxCines.setSelectedIndex(0);
        jComboBoxGeneros.setSelectedIndex(0);
        jTextFieldCal.setText("");
    }//GEN-LAST:event_jButtonGuardarPeliculaActionPerformed

    private void jButtonGuardarCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCineActionPerformed
        //Obtenemos los datos del cine
        String nombreCine = jTextFieldNombreCine.getText().trim();
        String direccionCine = jTextFieldDireccionCine.getText().trim();
        Cine cine;
        if (nombreCine.isEmpty() || direccionCine.isEmpty()) { //Los dos campos deben estar rellenos
            JOptionPane.showMessageDialog(rootPane, "Los campos nombre y dirección no pueden estar vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (CineDao.comprobarCine(nombreCine)) { //Comprobamos que no haya un cine con el mismo nombre
                JOptionPane.showMessageDialog(rootPane, "El cine ya existe", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                cine = new Cine(); //Creamos el cine y le ponemos los datos
                cine.setNombreCine(nombreCine);
                cine.setDireccionCine(direccionCine);
                CineDao.registrarCine(cine); //Lo registramos en la BD
                rellenarComboBoxCine(); //Actualizamos el comboBox de cines
                JOptionPane.showMessageDialog(rootPane, cine.getNombreCine() + " guardado", "Mensaje", JOptionPane.INFORMATION_MESSAGE); //Avisamos al usuario
                //Vaciamos los campos
                jTextFieldNombreCine.setText("");
                jTextFieldDireccionCine.setText("");
            }
        }
    }//GEN-LAST:event_jButtonGuardarCineActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        //Actualizamos las variables
        filtroGenero = jComboBoxGenerosFiltro.getSelectedItem().toString();
        filtroCine = jComboBoxCinesFiltro.getSelectedItem().toString();
        //Refrescamos la tabla obteniendo una lista filtrada
        refrescarTablaPeliculas(PeliculaDao.filtrarPeliculas(filtroGenero, filtroCine));
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    public void rellenarComboBoxCine() {
        //Vaciamos los comboBox de cines
        jComboBoxCines.removeAllItems();
        jComboBoxCines1.removeAllItems();
        jComboBoxCinesFiltro.removeAllItems();
        //Añadimos "Todos" al de filtrar
        jComboBoxCinesFiltro.addItem("Todos");
        ArrayList<Cine> listaCines = CineDao.listarCines(); //Obtenemos todos los cines
        if (listaCines != null) {
            for (Cine cine : listaCines) {
                //Los añadimos a los comboBox
                jComboBoxCines.addItem(cine.getNombreCine());
                jComboBoxCines1.addItem(cine.getNombreCine());
                jComboBoxCinesFiltro.addItem(cine.getNombreCine());
            }
        }
    }

    public void rellenarComboBoxPeliculas() {
        //Vaciamos el comboBox de peliculas
        jComboBoxTitulo.removeAllItems();
        ArrayList<Pelicula> listaPeliculas = PeliculaDao.listarPeliculas(); //Obtenemos todas las peliculas
        if (listaPeliculas != null) {
            for (Pelicula pelicula : listaPeliculas) {
                jComboBoxTitulo.addItem(pelicula.getNombrePelicula()); //Añadimos sus titulos al comboBox
            }
        }
    }

    public void rellenarComboBoxGenero() {
        //Vaciamos los comboBox de generos
        jComboBoxGeneros.removeAllItems();
        jComboBoxGeneros1.removeAllItems();
        jComboBoxGenerosFiltro.removeAllItems();
        //Añadimos "Todos" al de los filtros
        jComboBoxGenerosFiltro.addItem("Todos");
        ArrayList<Genero> listaGeneros = GeneroDao.listarGeneros(); //Obtenemos los generos
        if (listaGeneros != null) {
            for (Genero genero : listaGeneros) { 
                //Añadimos los generos a los comboBox
                jComboBoxGeneros.addItem(genero.getNombreGenero());
                jComboBoxGeneros1.addItem(genero.getNombreGenero());
                jComboBoxGenerosFiltro.addItem(genero.getNombreGenero());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoVista;
    private javax.swing.JButton jButtonEliminarPelicula;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonGuardarCine;
    private javax.swing.JButton jButtonGuardarPelicula;
    private javax.swing.JButton jButtonImprimirInforme;
    private javax.swing.JButton jButtonModificarPelicula;
    private javax.swing.JComboBox<String> jComboBoxCines;
    private javax.swing.JComboBox<String> jComboBoxCines1;
    private javax.swing.JComboBox<String> jComboBoxCinesFiltro;
    private javax.swing.JComboBox<String> jComboBoxFormatos;
    private javax.swing.JComboBox<String> jComboBoxGeneros;
    private javax.swing.JComboBox<String> jComboBoxGeneros1;
    private javax.swing.JComboBox<String> jComboBoxGenerosFiltro;
    private javax.swing.JComboBox<String> jComboBoxTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCal;
    private javax.swing.JLabel jLabelCal1;
    private javax.swing.JLabel jLabelCine;
    private javax.swing.JLabel jLabelCine1;
    private javax.swing.JLabel jLabelDireccionCine;
    private javax.swing.JLabel jLabelFiltroCine;
    private javax.swing.JLabel jLabelFiltroGenero;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelGenero1;
    private javax.swing.JLabel jLabelIcon1;
    private javax.swing.JLabel jLabelIcon2;
    private javax.swing.JLabel jLabelIcon3;
    private javax.swing.JLabel jLabelIcon4;
    private javax.swing.JLabel jLabelIcon5;
    private javax.swing.JLabel jLabelIcon6;
    private javax.swing.JLabel jLabelNombreCine;
    private javax.swing.JLabel jLabelNuevaPelicula;
    private javax.swing.JLabel jLabelNuevaPelicula1;
    private javax.swing.JLabel jLabelNuevoCine;
    private javax.swing.JLabel jLabelTituloPelicula;
    private javax.swing.JLabel jLabelTituloPelicula1;
    private javax.swing.JLabel jLabelVista;
    private javax.swing.JLabel jLabelVista1;
    private javax.swing.JPanel jPanelAñadirCine;
    private javax.swing.JPanel jPanelAñadirPelicula;
    private javax.swing.JPanel jPanelCamposCine;
    private javax.swing.JPanel jPanelCamposModificarPelicula;
    private javax.swing.JPanel jPanelCamposPelicula;
    private javax.swing.JPanel jPanelModificarPelicula;
    private javax.swing.JPanel jPanelSacarInforme;
    private javax.swing.JPanel jPanelTablaPeliculas;
    private javax.swing.JPanel jPanelTituloCine;
    private javax.swing.JPanel jPanelTituloPelicula;
    private javax.swing.JPanel jPanelTituloPelicula1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonNo1;
    private javax.swing.JRadioButton jRadioButtonSi;
    private javax.swing.JRadioButton jRadioButtonSi1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePeliculas;
    private javax.swing.JTextField jTextFieldCal;
    private javax.swing.JTextField jTextFieldCal1;
    private javax.swing.JTextField jTextFieldDireccionCine;
    private javax.swing.JTextField jTextFieldNombreCine;
    private javax.swing.JTextField jTextFieldTituloPelicula;
    // End of variables declaration//GEN-END:variables
}
