/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut6_actividad3.juego3;

/**
 *
 * @author Tarde
 */
public class JuegoMoverBola extends javax.swing.JFrame {

    /**
     * Creates new form JuegoMoverBola
     */
    public JuegoMoverBola() {
        initComponents();
        setTitle("Move a Ball");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelControles = new javax.swing.JPanel();
        jButtonUp = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        jButtonLeft = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelControles.setBackground(new java.awt.Color(255, 255, 255));
        jPanelControles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUp.setText("UP");
        jPanelControles.add(jButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 40));

        jButtonDown.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDown.setText("DOWN");
        jPanelControles.add(jButtonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 40));

        jButtonLeft.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLeft.setText("LEFT");
        jPanelControles.add(jButtonLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 40));

        jButtonRight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRight.setText("RIGHT");
        jPanelControles.add(jButtonRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 338, Short.MAX_VALUE)
                .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoMoverBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoMoverBola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonLeft;
    private javax.swing.JButton jButtonRight;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JPanel jPanelControles;
    // End of variables declaration//GEN-END:variables
}
