/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad3_1ejercicio4;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Danim2205
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    int grosor=0;
    boolean canPaint=false;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/actividad3_1ejercicio4/imgs/Logo.png")).getImage()); //Logo de la aplicación
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTotal = new javax.swing.JPanel();
        jPanelAreaDibujo = new javax.swing.JPanel();
        jLabelCoordenadas = new javax.swing.JLabel();
        jLabelGrosor = new javax.swing.JLabel();
        jTextFieldGrosor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTotal.setBackground(new java.awt.Color(60, 60, 60));
        jPanelTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAreaDibujo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAreaDibujo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelAreaDibujoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelAreaDibujoMouseMoved(evt);
            }
        });
        jPanelAreaDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAreaDibujoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAreaDibujoMouseExited(evt);
            }
        });
        jPanelAreaDibujo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCoordenadas.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jPanelAreaDibujo.add(jLabelCoordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelTotal.add(jPanelAreaDibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 580, 280));

        jLabelGrosor.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabelGrosor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrosor.setText("Grosor pincel:");
        jPanelTotal.add(jLabelGrosor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jTextFieldGrosor.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jTextFieldGrosor.setNextFocusableComponent(jPanelAreaDibujo);
        jTextFieldGrosor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldGrosorFocusLost(evt);
            }
        });
        jTextFieldGrosor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrosorActionPerformed(evt);
            }
        });
        jPanelTotal.add(jTextFieldGrosor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 25, 70, 30));

        getContentPane().add(jPanelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGrosorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldGrosorFocusLost
        if(jTextFieldGrosor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El grosor no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!isNumber(jTextFieldGrosor.getText())) {
            JOptionPane.showMessageDialog(this, "El grosor debe ser un numero entero positivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else grosor=Integer.parseInt(jTextFieldGrosor.getText());
    }//GEN-LAST:event_jTextFieldGrosorFocusLost

    private void jPanelAreaDibujoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaDibujoMouseDragged
        jLabelCoordenadas.setText("x="+evt.getX()+", y="+evt.getY()); //getX y getY devuelve las coordenadas dentro del panel
        if(canPaint){
            Graphics g=jPanelAreaDibujo.getGraphics(); //Importante obtener los graficos del área de dibujo y no de la ventana
            g.setColor(Color.BLACK); //Pintaremos de color negro
            g.fillOval(evt.getX(),evt.getY(),grosor,grosor); 
        }
    }//GEN-LAST:event_jPanelAreaDibujoMouseDragged

    private void jPanelAreaDibujoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaDibujoMouseMoved
        jLabelCoordenadas.setText("x="+evt.getX()+", y="+evt.getY()); //getX y getY devuelve las coordenadas dentro del panel
    }//GEN-LAST:event_jPanelAreaDibujoMouseMoved

    private void jPanelAreaDibujoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaDibujoMouseEntered
        canPaint=true; //Si estamos dentro del panel, podemos pintar
    }//GEN-LAST:event_jPanelAreaDibujoMouseEntered

    private void jPanelAreaDibujoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaDibujoMouseExited
        jLabelCoordenadas.setText(""); //Escondemos las coordenadas eliminando el texto
        canPaint=false; //Si salimos del panel, no podemos pintar
    }//GEN-LAST:event_jPanelAreaDibujoMouseExited

    private void jTextFieldGrosorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrosorActionPerformed
        jPanelAreaDibujo.requestFocus();
    }//GEN-LAST:event_jTextFieldGrosorActionPerformed

    private boolean isNumber(String s){
        return s.matches("[0-9]+");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCoordenadas;
    private javax.swing.JLabel jLabelGrosor;
    private javax.swing.JPanel jPanelAreaDibujo;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JTextField jTextFieldGrosor;
    // End of variables declaration//GEN-END:variables
}
