/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad4;

import java.awt.Color;

/**
 *
 * @author Tarde
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPregunta1 = new javax.swing.ButtonGroup();
        buttonGroupPregunta2 = new javax.swing.ButtonGroup();
        buttonGroupPregunta3 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelPregunta1 = new javax.swing.JLabel();
        jLabelPregunta2 = new javax.swing.JLabel();
        jLabelPregunta3 = new javax.swing.JLabel();
        jLabelPregunta4 = new javax.swing.JLabel();
        jRadioButtonPregunta1A = new javax.swing.JRadioButton();
        jRadioButtonPregunta1B = new javax.swing.JRadioButton();
        jRadioButtonPregunta1C = new javax.swing.JRadioButton();
        jRadioButtonPreguntaD = new javax.swing.JRadioButton();
        jRadioButtonPregunta2A = new javax.swing.JRadioButton();
        jRadioButtonPregunta2B = new javax.swing.JRadioButton();
        jRadioButtonPregunta2C = new javax.swing.JRadioButton();
        jRadioButtonPregunta2D = new javax.swing.JRadioButton();
        jRadioButtonPregunta3A = new javax.swing.JRadioButton();
        jRadioButtonPregunta3B = new javax.swing.JRadioButton();
        jRadioButtonPregunta3C = new javax.swing.JRadioButton();
        jRadioButtonPregunta3D = new javax.swing.JRadioButton();
        jButtonCorregir = new javax.swing.JButton();
        jCheckBoxPregunta4A = new javax.swing.JCheckBox();
        jCheckBoxPregunta4B = new javax.swing.JCheckBox();
        jCheckBoxPregunta4C = new javax.swing.JCheckBox();
        jCheckBoxPregunta4D = new javax.swing.JCheckBox();
        jLabelAciertos = new javax.swing.JLabel();
        jLabelResultado1 = new javax.swing.JLabel();
        jLabelResultado2 = new javax.swing.JLabel();
        jLabelResultado3 = new javax.swing.JLabel();
        jLabelResultado4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        setSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Ingrese las respuestas correctas");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(190, 30, 370, 29);

        jLabelPregunta1.setText("4*6+3+2*2");
        getContentPane().add(jLabelPregunta1);
        jLabelPregunta1.setBounds(30, 120, 67, 16);

        jLabelPregunta2.setText("Nombre del quinto planeta");
        getContentPane().add(jLabelPregunta2);
        jLabelPregunta2.setBounds(30, 170, 151, 16);

        jLabelPregunta3.setText("Palabra con error ortográfico");
        getContentPane().add(jLabelPregunta3);
        jLabelPregunta3.setBounds(30, 220, 166, 16);

        jLabelPregunta4.setText("Sinónimos de inteligente");
        getContentPane().add(jLabelPregunta4);
        jLabelPregunta4.setBounds(30, 270, 140, 16);

        buttonGroupPregunta1.add(jRadioButtonPregunta1A);
        jRadioButtonPregunta1A.setText("58");
        getContentPane().add(jRadioButtonPregunta1A);
        jRadioButtonPregunta1A.setBounds(230, 120, 43, 25);

        buttonGroupPregunta1.add(jRadioButtonPregunta1B);
        jRadioButtonPregunta1B.setText("34");
        getContentPane().add(jRadioButtonPregunta1B);
        jRadioButtonPregunta1B.setBounds(330, 120, 43, 25);

        buttonGroupPregunta1.add(jRadioButtonPregunta1C);
        jRadioButtonPregunta1C.setText("31");
        getContentPane().add(jRadioButtonPregunta1C);
        jRadioButtonPregunta1C.setBounds(430, 120, 43, 25);

        buttonGroupPregunta1.add(jRadioButtonPreguntaD);
        jRadioButtonPreguntaD.setText("40");
        getContentPane().add(jRadioButtonPreguntaD);
        jRadioButtonPreguntaD.setBounds(530, 120, 43, 25);

        buttonGroupPregunta2.add(jRadioButtonPregunta2A);
        jRadioButtonPregunta2A.setText("Marte");
        getContentPane().add(jRadioButtonPregunta2A);
        jRadioButtonPregunta2A.setBounds(230, 170, 61, 25);

        buttonGroupPregunta2.add(jRadioButtonPregunta2B);
        jRadioButtonPregunta2B.setText("Júpiter");
        getContentPane().add(jRadioButtonPregunta2B);
        jRadioButtonPregunta2B.setBounds(330, 170, 67, 25);

        buttonGroupPregunta2.add(jRadioButtonPregunta2C);
        jRadioButtonPregunta2C.setText("Tierra");
        getContentPane().add(jRadioButtonPregunta2C);
        jRadioButtonPregunta2C.setBounds(430, 170, 63, 25);

        buttonGroupPregunta2.add(jRadioButtonPregunta2D);
        jRadioButtonPregunta2D.setText("Saturno");
        getContentPane().add(jRadioButtonPregunta2D);
        jRadioButtonPregunta2D.setBounds(530, 170, 73, 25);

        buttonGroupPregunta3.add(jRadioButtonPregunta3A);
        jRadioButtonPregunta3A.setText("Ola");
        getContentPane().add(jRadioButtonPregunta3A);
        jRadioButtonPregunta3A.setBounds(230, 220, 47, 25);

        buttonGroupPregunta3.add(jRadioButtonPregunta3B);
        jRadioButtonPregunta3B.setText("Desición");
        getContentPane().add(jRadioButtonPregunta3B);
        jRadioButtonPregunta3B.setBounds(330, 220, 75, 25);

        buttonGroupPregunta3.add(jRadioButtonPregunta3C);
        jRadioButtonPregunta3C.setText("Hay");
        getContentPane().add(jRadioButtonPregunta3C);
        jRadioButtonPregunta3C.setBounds(430, 220, 49, 25);

        buttonGroupPregunta3.add(jRadioButtonPregunta3D);
        jRadioButtonPregunta3D.setText("Ahí");
        getContentPane().add(jRadioButtonPregunta3D);
        jRadioButtonPregunta3D.setBounds(530, 220, 47, 25);

        jButtonCorregir.setText("Corregir");
        jButtonCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorregirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCorregir);
        jButtonCorregir.setBounds(190, 320, 400, 25);

        jCheckBoxPregunta4A.setText("Sagaz");
        getContentPane().add(jCheckBoxPregunta4A);
        jCheckBoxPregunta4A.setBounds(230, 270, 63, 25);

        jCheckBoxPregunta4B.setText("Listo");
        getContentPane().add(jCheckBoxPregunta4B);
        jCheckBoxPregunta4B.setBounds(330, 270, 55, 25);

        jCheckBoxPregunta4C.setText("Lerdo");
        getContentPane().add(jCheckBoxPregunta4C);
        jCheckBoxPregunta4C.setBounds(430, 270, 61, 25);

        jCheckBoxPregunta4D.setText("Astuto");
        getContentPane().add(jCheckBoxPregunta4D);
        jCheckBoxPregunta4D.setBounds(530, 270, 65, 25);

        jLabelAciertos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jLabelAciertos);
        jLabelAciertos.setBounds(350, 360, 100, 30);

        jLabelResultado1.setToolTipText("");
        getContentPane().add(jLabelResultado1);
        jLabelResultado1.setBounds(630, 120, 80, 20);
        getContentPane().add(jLabelResultado2);
        jLabelResultado2.setBounds(630, 170, 80, 20);
        getContentPane().add(jLabelResultado3);
        jLabelResultado3.setBounds(630, 220, 80, 20);
        getContentPane().add(jLabelResultado4);
        jLabelResultado4.setBounds(630, 270, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorregirActionPerformed
        int aciertos=0;
        if (jRadioButtonPregunta1C.isSelected()){
            aciertos++;
            jLabelResultado1.setText("Correcto");
            jLabelResultado1.setForeground(Color.green);
        }
        else{
            jLabelResultado1.setText("Incorrecto");
            jLabelResultado1.setForeground(Color.red);
        }
        if (jRadioButtonPregunta2B.isSelected()){
            aciertos++;
            jLabelResultado2.setText("Correcto");
            jLabelResultado2.setForeground(Color.green);
        }
        else{
            jLabelResultado2.setText("Incorrecto");
            jLabelResultado2.setForeground(Color.red);
        }
        if (jRadioButtonPregunta3B.isSelected()){
            aciertos++;
            jLabelResultado3.setText("Correcto");
            jLabelResultado3.setForeground(Color.green);
        }
        else{
            jLabelResultado3.setText("Incorrecto");
            jLabelResultado3.setForeground(Color.red);
        }
        if (jCheckBoxPregunta4A.isSelected() && jCheckBoxPregunta4B.isSelected() && jCheckBoxPregunta4D.isSelected() && !jCheckBoxPregunta4C.isSelected()){
            aciertos++;
            jLabelResultado4.setText("Correcto");
            jLabelResultado4.setForeground(Color.green);
        }
        else{
            jLabelResultado4.setText("Incorrecto");
            jLabelResultado4.setForeground(Color.red);
        }
        jLabelAciertos.setText("Aciertos: "+aciertos+"/4");
    }//GEN-LAST:event_jButtonCorregirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPregunta1;
    private javax.swing.ButtonGroup buttonGroupPregunta2;
    private javax.swing.ButtonGroup buttonGroupPregunta3;
    private javax.swing.JButton jButtonCorregir;
    private javax.swing.JCheckBox jCheckBoxPregunta4A;
    private javax.swing.JCheckBox jCheckBoxPregunta4B;
    private javax.swing.JCheckBox jCheckBoxPregunta4C;
    private javax.swing.JCheckBox jCheckBoxPregunta4D;
    private javax.swing.JLabel jLabelAciertos;
    private javax.swing.JLabel jLabelPregunta1;
    private javax.swing.JLabel jLabelPregunta2;
    private javax.swing.JLabel jLabelPregunta3;
    private javax.swing.JLabel jLabelPregunta4;
    private javax.swing.JLabel jLabelResultado1;
    private javax.swing.JLabel jLabelResultado2;
    private javax.swing.JLabel jLabelResultado3;
    private javax.swing.JLabel jLabelResultado4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JRadioButton jRadioButtonPregunta1A;
    private javax.swing.JRadioButton jRadioButtonPregunta1B;
    private javax.swing.JRadioButton jRadioButtonPregunta1C;
    private javax.swing.JRadioButton jRadioButtonPregunta2A;
    private javax.swing.JRadioButton jRadioButtonPregunta2B;
    private javax.swing.JRadioButton jRadioButtonPregunta2C;
    private javax.swing.JRadioButton jRadioButtonPregunta2D;
    private javax.swing.JRadioButton jRadioButtonPregunta3A;
    private javax.swing.JRadioButton jRadioButtonPregunta3B;
    private javax.swing.JRadioButton jRadioButtonPregunta3C;
    private javax.swing.JRadioButton jRadioButtonPregunta3D;
    private javax.swing.JRadioButton jRadioButtonPreguntaD;
    // End of variables declaration//GEN-END:variables
}
