/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad3_1ejercicio3;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Danim2205
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/actividad3_1ejercicio3/imgs/Cuadrado.png")).getImage()); //Logo de la aplicación
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelCuadrado = new javax.swing.JLabel();
        jLabelRectangulo = new javax.swing.JLabel();
        jLabelTriangulo = new javax.swing.JLabel();
        jLabelRombo = new javax.swing.JLabel();
        jLabelEnunciado = new javax.swing.JLabel();
        jTextFieldCuadrado = new javax.swing.JTextField();
        jTextFieldRectangulo = new javax.swing.JTextField();
        jTextFieldTriangulo = new javax.swing.JTextField();
        jTextFieldRombo = new javax.swing.JTextField();
        jLabelResultado = new javax.swing.JLabel();
        jButtonCorregir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3_1ejercicio3/imgs/Cuadrado.png"))); // NOI18N
        jPanel.add(jLabelCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabelRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3_1ejercicio3/imgs/Rectangulo.png"))); // NOI18N
        jPanel.add(jLabelRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabelTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3_1ejercicio3/imgs/Triangulo.png"))); // NOI18N
        jPanel.add(jLabelTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabelRombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3_1ejercicio3/imgs/Rombo.png"))); // NOI18N
        jPanel.add(jLabelRombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabelEnunciado.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEnunciado.setForeground(new java.awt.Color(0, 0, 255));
        jLabelEnunciado.setText("ESCRIBE LOS NOMBRES DE LAS FIGURAS GEOMÉTRICAS");
        jPanel.add(jLabelEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextFieldCuadrado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldCuadrado.setForeground(new java.awt.Color(0, 0, 255));
        jPanel.add(jTextFieldCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 170, 150, -1));

        jTextFieldRectangulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldRectangulo.setForeground(new java.awt.Color(0, 0, 255));
        jPanel.add(jTextFieldRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 310, 150, -1));

        jTextFieldTriangulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldTriangulo.setForeground(new java.awt.Color(0, 0, 255));
        jPanel.add(jTextFieldTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 170, 150, -1));

        jTextFieldRombo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldRombo.setForeground(new java.awt.Color(0, 0, 255));
        jPanel.add(jTextFieldRombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 310, 150, -1));

        jLabelResultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelResultado.setForeground(new java.awt.Color(0, 0, 255));
        jPanel.add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jButtonCorregir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCorregir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCorregir.setForeground(new java.awt.Color(0, 0, 255));
        jButtonCorregir.setText("CORREGIR");
        jButtonCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorregirActionPerformed(evt);
            }
        });
        jPanel.add(jButtonCorregir, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 340, 150, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3_1ejercicio3/imgs/FondoCuadricula.png"))); // NOI18N
        jPanel.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorregirActionPerformed
        int contadorAciertos=0;
        //Obtenemos las respuestas y las guardamos en variables
        String respuestaCuadrado=jTextFieldCuadrado.getText();
        String respuestaRectangulo=jTextFieldRectangulo.getText();
        String respuestaTriangulo=jTextFieldTriangulo.getText();
        String respuestaRombo=jTextFieldRombo.getText();
        
        //Comprobamos respuestas, contamos aciertos y cambiamos colores en base a lo anterior
        if(respuestaCuadrado.equalsIgnoreCase("Cuadrado")){ //Si la respuesta del cuadrado es correcta
            jTextFieldCuadrado.setForeground(Color.GREEN); //Ponemos el texto del textField a verde
            contadorAciertos++; //Sumamos 1 acierto
        }
        else jTextFieldCuadrado.setForeground(Color.RED); //Si no es correcto, ponemos el texto del textField a rojo
        if(respuestaRectangulo.equalsIgnoreCase("Rectangulo") || respuestaRectangulo.equalsIgnoreCase("Rectángulo")){ //Si la respuesta del rectángulo es correcta
            jTextFieldRectangulo.setForeground(Color.GREEN); //Ponemos el texto del textField a verde
            contadorAciertos++; //Sumamos 1 acierto
        }
        else jTextFieldRectangulo.setForeground(Color.RED); //Si no es correcto, ponemos el texto del textField a rojo
        if(respuestaTriangulo.equalsIgnoreCase("Triangulo") ||respuestaTriangulo.equalsIgnoreCase("Triángulo")){ //Si la respuesta del triángulo es correcta
            jTextFieldTriangulo.setForeground(Color.GREEN); //Ponemos el texto del textField a verde
            contadorAciertos++; //Sumamos 1 acierto
        }
        else jTextFieldTriangulo.setForeground(Color.RED); //Si no es correcto, ponemos el texto del textField a rojo
        if(respuestaRombo.equalsIgnoreCase("Rombo")){ //Si la respuesta del rombo es correcta
            jTextFieldRombo.setForeground(Color.GREEN); //Ponemos el texto del textField a verde
            contadorAciertos++; //Sumamos 1 acierto
        }
        else jTextFieldRombo.setForeground(Color.RED); //Si no es correcto, ponemos el texto del textField a rojo
        
        jLabelResultado.setText("Aciertos: "+contadorAciertos+"/4"); //Mensaje final de aciertos
    }//GEN-LAST:event_jButtonCorregirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCorregir;
    private javax.swing.JLabel jLabelCuadrado;
    private javax.swing.JLabel jLabelEnunciado;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRectangulo;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelRombo;
    private javax.swing.JLabel jLabelTriangulo;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTextFieldCuadrado;
    private javax.swing.JTextField jTextFieldRectangulo;
    private javax.swing.JTextField jTextFieldRombo;
    private javax.swing.JTextField jTextFieldTriangulo;
    // End of variables declaration//GEN-END:variables
}
