/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut6_actividad1;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static practica1ut6_actividad1.Bingo.tarjeta;

/**
 *
 * @author Tarde
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        setTitle("Bingo");
        Bingo.rellenarTarjeta();
        crearTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGenerarAleatorio = new javax.swing.JButton();
        jLabelNumeroActual = new javax.swing.JLabel();
        jPanelTarjeta = new javax.swing.JPanel();
        jLabelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonGenerarAleatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGenerarAleatorio.setText("GENERAR NÚMERO ALEATORIO");
        jButtonGenerarAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarAleatorioActionPerformed(evt);
            }
        });

        jLabelNumeroActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNumeroActual.setText("NÚMERO ACTUAL: ");

        jPanelTarjeta.setLayout(new java.awt.GridLayout(5, 5));

        jLabelResultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 90, Short.MAX_VALUE)
                        .addComponent(jButtonGenerarAleatorio)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNumeroActual)
                        .addGap(157, 157, 157))))
            .addComponent(jPanelTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGenerarAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNumeroActual)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelResultado)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void crearTablero() {
        JButton boton = new JButton();
        for (int i = 0; i < Bingo.tarjeta.length; i++) {
            for (int j = 0; j < Bingo.tarjeta[0].length; j++) {
                jPanelTarjeta.add(new JButton(Bingo.tarjeta[i][j].getValor()+""));
            }
        }
    }
    private void jButtonGenerarAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarAleatorioActionPerformed
        int aleatorio = (int) (Math.random() * 75 + 1);
        jLabelNumeroActual.setText("NÚMERO ACTUAL: " + aleatorio);
        actualizarEstado(aleatorio);
    }//GEN-LAST:event_jButtonGenerarAleatorioActionPerformed

    private boolean comprobarVictoria() {
        for (int i = 0; i < tarjeta.length; i++) {
            for (int j = 0; j < tarjeta[0].length; j++) {
                if (!tarjeta[i][j].isDescubierta()) {
                    return false;
                }
            }
        }
        return true;
    }

    private void actualizarEstado(int aleatorio) {
        for (int i = 0; i < tarjeta.length; i++) {
            for (int j = 0; j < tarjeta[0].length; j++) {
                if (tarjeta[i][j].getValor() == aleatorio) {
                    tarjeta[i][j].setDescubierta(true);
                    JButton boton = (JButton) jPanelTarjeta.getComponent((tarjeta.length * i) + j);
                    boton.setBackground(Color.GREEN);
                    if (comprobarVictoria()) {
                        JOptionPane.showMessageDialog(this, "Has ganado!", "VICTORIA", JOptionPane.INFORMATION_MESSAGE);
                        jLabelResultado.setText("Victoria!");
                        jButtonGenerarAleatorio.setEnabled(false);
                    }
                    return; //Paramos la ejecucion del metodo para no perder tiempo recorriendo el for, ya que solo hay una casilla con ese numero
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarAleatorio;
    private javax.swing.JLabel jLabelNumeroActual;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanelTarjeta;
    // End of variables declaration//GEN-END:variables
}
