/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica5ut3.gui;

/**
 *
 * @author Tarde
 */
public class EleccionPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form EleccionPersonaje
     */
    public EleccionPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelImagenFondo = new jpanelimagen.JPanelImagen();
        jPanelPersonajes = new javax.swing.JPanel();
        jPanelImagenPersonaje1 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje2 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje3 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje4 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje5 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje6 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje7 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje8 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje9 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje10 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje11 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje12 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje13 = new jpanelimagen.JPanelImagen();
        jPanelImagenPersonaje14 = new jpanelimagen.JPanelImagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 526));
        setPreferredSize(new java.awt.Dimension(1000, 556));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImagenFondo.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPersonajes.setOpaque(false);
        jPanelPersonajes.setLayout(new java.awt.GridBagLayout());

        jPanelImagenPersonaje1.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje1.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje1.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje1.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje1Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje1);
        jPanelImagenPersonaje1.setLayout(jPanelImagenPersonaje1Layout);
        jPanelImagenPersonaje1Layout.setHorizontalGroup(
            jPanelImagenPersonaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje1Layout.setVerticalGroup(
            jPanelImagenPersonaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje1, gridBagConstraints);

        jPanelImagenPersonaje2.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje2.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje2.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje2.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje2Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje2);
        jPanelImagenPersonaje2.setLayout(jPanelImagenPersonaje2Layout);
        jPanelImagenPersonaje2Layout.setHorizontalGroup(
            jPanelImagenPersonaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje2Layout.setVerticalGroup(
            jPanelImagenPersonaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje2, gridBagConstraints);

        jPanelImagenPersonaje3.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje3.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje3.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje3.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje3Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje3);
        jPanelImagenPersonaje3.setLayout(jPanelImagenPersonaje3Layout);
        jPanelImagenPersonaje3Layout.setHorizontalGroup(
            jPanelImagenPersonaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje3Layout.setVerticalGroup(
            jPanelImagenPersonaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje3, gridBagConstraints);

        jPanelImagenPersonaje4.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje4.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje4.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje4.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje4Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje4);
        jPanelImagenPersonaje4.setLayout(jPanelImagenPersonaje4Layout);
        jPanelImagenPersonaje4Layout.setHorizontalGroup(
            jPanelImagenPersonaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje4Layout.setVerticalGroup(
            jPanelImagenPersonaje4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje4, gridBagConstraints);

        jPanelImagenPersonaje5.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje5.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje5.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje5.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje5Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje5);
        jPanelImagenPersonaje5.setLayout(jPanelImagenPersonaje5Layout);
        jPanelImagenPersonaje5Layout.setHorizontalGroup(
            jPanelImagenPersonaje5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje5Layout.setVerticalGroup(
            jPanelImagenPersonaje5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje5, gridBagConstraints);

        jPanelImagenPersonaje6.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje6.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje6.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje6.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje6Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje6);
        jPanelImagenPersonaje6.setLayout(jPanelImagenPersonaje6Layout);
        jPanelImagenPersonaje6Layout.setHorizontalGroup(
            jPanelImagenPersonaje6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje6Layout.setVerticalGroup(
            jPanelImagenPersonaje6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje6, gridBagConstraints);

        jPanelImagenPersonaje7.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje7.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje7.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje7.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje7Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje7);
        jPanelImagenPersonaje7.setLayout(jPanelImagenPersonaje7Layout);
        jPanelImagenPersonaje7Layout.setHorizontalGroup(
            jPanelImagenPersonaje7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje7Layout.setVerticalGroup(
            jPanelImagenPersonaje7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje7, gridBagConstraints);

        jPanelImagenPersonaje8.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje8.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje8.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje8.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje8Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje8);
        jPanelImagenPersonaje8.setLayout(jPanelImagenPersonaje8Layout);
        jPanelImagenPersonaje8Layout.setHorizontalGroup(
            jPanelImagenPersonaje8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje8Layout.setVerticalGroup(
            jPanelImagenPersonaje8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje8, gridBagConstraints);

        jPanelImagenPersonaje9.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje9.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje9.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje9.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje9Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje9);
        jPanelImagenPersonaje9.setLayout(jPanelImagenPersonaje9Layout);
        jPanelImagenPersonaje9Layout.setHorizontalGroup(
            jPanelImagenPersonaje9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje9Layout.setVerticalGroup(
            jPanelImagenPersonaje9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje9, gridBagConstraints);

        jPanelImagenPersonaje10.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje10.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje10.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje10.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje10Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje10);
        jPanelImagenPersonaje10.setLayout(jPanelImagenPersonaje10Layout);
        jPanelImagenPersonaje10Layout.setHorizontalGroup(
            jPanelImagenPersonaje10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje10Layout.setVerticalGroup(
            jPanelImagenPersonaje10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje10, gridBagConstraints);

        jPanelImagenPersonaje11.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje11.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje11.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje11.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje11Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje11);
        jPanelImagenPersonaje11.setLayout(jPanelImagenPersonaje11Layout);
        jPanelImagenPersonaje11Layout.setHorizontalGroup(
            jPanelImagenPersonaje11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje11Layout.setVerticalGroup(
            jPanelImagenPersonaje11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje11, gridBagConstraints);

        jPanelImagenPersonaje12.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje12.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje12.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje12.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje12Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje12);
        jPanelImagenPersonaje12.setLayout(jPanelImagenPersonaje12Layout);
        jPanelImagenPersonaje12Layout.setHorizontalGroup(
            jPanelImagenPersonaje12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje12Layout.setVerticalGroup(
            jPanelImagenPersonaje12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje12, gridBagConstraints);

        jPanelImagenPersonaje13.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje13.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje13.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje13.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje13Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje13);
        jPanelImagenPersonaje13.setLayout(jPanelImagenPersonaje13Layout);
        jPanelImagenPersonaje13Layout.setHorizontalGroup(
            jPanelImagenPersonaje13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje13Layout.setVerticalGroup(
            jPanelImagenPersonaje13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje13, gridBagConstraints);

        jPanelImagenPersonaje14.setBackground(new java.awt.Color(0, 0, 0));
        jPanelImagenPersonaje14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanelImagenPersonaje14.setImagenFondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"),0.5f,1.0f));
        jPanelImagenPersonaje14.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanelImagenPersonaje14.setSize(new java.awt.Dimension(100, 150));

        javax.swing.GroupLayout jPanelImagenPersonaje14Layout = new javax.swing.GroupLayout(jPanelImagenPersonaje14);
        jPanelImagenPersonaje14.setLayout(jPanelImagenPersonaje14Layout);
        jPanelImagenPersonaje14Layout.setHorizontalGroup(
            jPanelImagenPersonaje14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanelImagenPersonaje14Layout.setVerticalGroup(
            jPanelImagenPersonaje14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelPersonajes.add(jPanelImagenPersonaje14, gridBagConstraints);

        jPanelImagenFondo.add(jPanelPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 550, 480));

        getContentPane().add(jPanelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleccionPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jpanelimagen.JPanelImagen jPanelImagenFondo;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje1;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje10;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje11;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje12;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje13;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje14;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje2;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje3;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje4;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje5;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje6;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje7;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje8;
    private jpanelimagen.JPanelImagen jPanelImagenPersonaje9;
    private javax.swing.JPanel jPanelPersonajes;
    // End of variables declaration//GEN-END:variables
}
