/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javahelpexample2;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;

/**
 *
 * @author Tarde
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        ayuda();
    }
    
    private void ayuda(){
        try {
            File file=new File("help"+File.separator+"help_set.hs");
            URL hsUrl=file.toURI().toURL();
            HelpSet helpSet=new HelpSet(getClass().getClassLoader(),hsUrl);
            HelpBroker helpBroker=helpSet.createHelpBroker();
            helpBroker.enableHelpOnButton(jMenuItemAyuda,"introduccion",helpSet);
            helpBroker.enableHelpKey(getRootPane(),"introduccion",helpSet);
            helpBroker.enableHelpKey(jButtonIntroduccion,"introduccion",helpSet);
            helpBroker.enableHelpKey(jButtonInstalacion,"instalacion",helpSet);
            helpBroker.enableHelpKey(jButtonFuncionesPrincipales,"funciones_principales",helpSet);
            helpBroker.enableHelpKey(jButtonInterfazUsuario,"interfaz_usuario",helpSet);
            helpBroker.enableHelpKey(jButtonSolucionProblemas,"solucion_problemas",helpSet);
            helpBroker.enableHelpKey(jButtonAcercaDe,"acercade",helpSet);
            helpBroker.enableHelpOnButton(jButtonIntroduccion,"introduccion",helpSet);
            helpBroker.enableHelpOnButton(jButtonInstalacion,"instalacion",helpSet);
            helpBroker.enableHelpOnButton(jButtonFuncionesPrincipales,"funciones_principales",helpSet);
            helpBroker.enableHelpOnButton(jButtonInterfazUsuario,"interfaz_usuario",helpSet);
            helpBroker.enableHelpOnButton(jButtonSolucionProblemas,"solucion_problemas",helpSet);
            helpBroker.enableHelpOnButton(jButtonAcercaDe,"acercade",helpSet);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotones = new javax.swing.JPanel();
        jButtonIntroduccion = new javax.swing.JButton();
        jButtonInstalacion = new javax.swing.JButton();
        jButtonFuncionesPrincipales = new javax.swing.JButton();
        jButtonInterfazUsuario = new javax.swing.JButton();
        jButtonSolucionProblemas = new javax.swing.JButton();
        jButtonAcercaDe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBotones.setLayout(new java.awt.GridLayout(3, 2));

        jButtonIntroduccion.setText("Introduccion");
        jPanelBotones.add(jButtonIntroduccion);

        jButtonInstalacion.setText("Instalacion");
        jPanelBotones.add(jButtonInstalacion);

        jButtonFuncionesPrincipales.setText("Funciones principales");
        jPanelBotones.add(jButtonFuncionesPrincipales);

        jButtonInterfazUsuario.setText("Interfaz de usuario");
        jButtonInterfazUsuario.setToolTipText("");
        jPanelBotones.add(jButtonInterfazUsuario);

        jButtonSolucionProblemas.setText("Solucion de problemas");
        jButtonSolucionProblemas.setToolTipText("");
        jPanelBotones.add(jButtonSolucionProblemas);

        jButtonAcercaDe.setText("Acerca De");
        jButtonAcercaDe.setToolTipText("");
        jPanelBotones.add(jButtonAcercaDe);

        jMenu1.setText("Ayuda");

        jMenuItemAyuda.setText("Mostrar ayuda");
        jMenu1.add(jMenuItemAyuda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcercaDe;
    private javax.swing.JButton jButtonFuncionesPrincipales;
    private javax.swing.JButton jButtonInstalacion;
    private javax.swing.JButton jButtonInterfazUsuario;
    private javax.swing.JButton jButtonIntroduccion;
    private javax.swing.JButton jButtonSolucionProblemas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JPanel jPanelBotones;
    // End of variables declaration//GEN-END:variables
}
