/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.gui;

import examen.logica.Proveedor;
import examen.logica.ListaProveedores;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Tarde
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/Logo.png")).getImage()); //Ponemos el icono a la interfaz
        cargarModeloComboBox();//Cargamos el modelo con banderas del comboBox
        cargarDatosValidationPanel(); //Creamos las restricciones del panel de validacion
    }

    private void cargarModeloComboBox(){
        DefaultComboBoxModel<String>modelo=new DefaultComboBoxModel<String>();
        //Añadimos los elementos
        modelo.addElement("Bélgica");
        modelo.addElement("Brasil");
        modelo.addElement("España");
        modelo.addElement("Estados Unidos");
        jComboBoxNacionalidad.setModel(modelo); //Damos el modelo al ComboBox
        jComboBoxNacionalidad.setSelectedIndex(2); //Por defecto esta seleccionado España
        jComboBoxNacionalidad.setRenderer(new ListCellRenderer<String>(){
            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label=new JLabel(); //Creamos un Label
                //Para cada label pondremos un icono con su bandera y el nombre de su pais
                switch(value){
                    case "Bélgica":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/banderas/Bélgica.png")));
                        label.setText("Bélgica");
                        break;
                    case "Brasil":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/banderas/Brasil.png")));
                        label.setText("Brasil");
                        break;
                    case "España":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/banderas/España.png")));
                        label.setText("España");
                        break;
                    case "Estados Unidos":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/banderas/Estados Unidos.png")));
                        label.setText("Estados Unidos");
                        break;
                }
                if(isSelected){
                    label.setBackground(list.getSelectionBackground());
                    label.setOpaque(true);
                }
                return label;
            }
            
        });
    }
    private void cargarDatosValidationPanel(){
        ValidationGroup group=validationPanel.getValidationGroup(); //Creamos el validation group
        //Añadimos los componentes con sus restricciones
        //Todos deben estar rellenos, ninguno vacio
        group.add(jTextFieldNumeroEmpresa,StringValidators.REQUIRE_VALID_INTEGER); //El numero de la empresa debe ser un numero entero
        group.add(jTextFieldNombreEmpresa,StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldDireccion,StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldEmail,StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldTelefono,StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldTelefono,StringValidators.REQUIRE_VALID_INTEGER); //El telefono debe tener solo numeros
        group.add(jTextFieldTelefono,StringValidators.minLength(9)); //El telefono debe medir 9 caracteres de minimo y maximo
        group.add(jTextFieldTelefono,StringValidators.maxLength(9));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelLogo = new jpanellogo.JPanelLogo();
        jPanelDatos = new javax.swing.JPanel();
        jLabelNumeroEmpresa = new javax.swing.JLabel();
        jLabelNombreEmpresa = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelNacionalidad = new javax.swing.JLabel();
        jTextFieldNumeroEmpresa = new javax.swing.JTextField();
        jTextFieldNombreEmpresa = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jComboBoxNacionalidad = new javax.swing.JComboBox<>();
        jButtonInsertar = new javax.swing.JButton();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jLabelIconoNombreEmpresa = new javax.swing.JLabel();
        jLabelIconoNumeroEmpresa = new javax.swing.JLabel();
        jLabelIconoDireccion = new javax.swing.JLabel();
        jLabelIconoEmail = new javax.swing.JLabel();
        jLabelIconoTelefono = new javax.swing.JLabel();
        jLabelIconoNacionalidad = new javax.swing.JLabel();
        jLabelOficina = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonVerDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(141, 0, 0));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelMain.add(jPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)), "DATOS PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelDatos.setOpaque(false);
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumeroEmpresa.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelNumeroEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroEmpresa.setText("Numero empresa:");
        jPanelDatos.add(jLabelNumeroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelNombreEmpresa.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelNombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreEmpresa.setText("Nombre empresa:");
        jPanelDatos.add(jLabelNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelDireccion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDireccion.setText("Dirección:");
        jPanelDatos.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");
        jPanelDatos.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Teléfono:");
        jPanelDatos.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabelNacionalidad.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelNacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNacionalidad.setText("Nacionalidad:");
        jPanelDatos.add(jLabelNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextFieldNumeroEmpresa.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextFieldNumeroEmpresa.setName("Numero empresa"); // NOI18N
        jPanelDatos.add(jTextFieldNumeroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, -1));

        jTextFieldNombreEmpresa.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextFieldNombreEmpresa.setName("Nombre empresa"); // NOI18N
        jPanelDatos.add(jTextFieldNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, -1));

        jTextFieldDireccion.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextFieldDireccion.setName("Direccion"); // NOI18N
        jPanelDatos.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 170, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextFieldEmail.setName("Email"); // NOI18N
        jPanelDatos.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, -1));

        jTextFieldTelefono.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextFieldTelefono.setName("Telefono"); // NOI18N
        jPanelDatos.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, -1));

        jComboBoxNacionalidad.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jComboBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bélgica", "Brasil", "España", "Estados Unidos" }));
        jComboBoxNacionalidad.setSelectedIndex(2);
        jPanelDatos.add(jComboBoxNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 170, -1));

        jButtonInsertar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButtonInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/insertar.png"))); // NOI18N
        jButtonInsertar.setText("INSERTAR");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });
        jPanelDatos.add(jButtonInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        validationPanel.setBackground(new java.awt.Color(0, 0, 0));
        validationPanel.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        validationPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                validationPanelStateChanged(evt);
            }
        });
        jPanelDatos.add(validationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 420, -1));

        jLabelIconoNombreEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Edificio.png"))); // NOI18N
        jPanelDatos.add(jLabelIconoNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabelIconoNumeroEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/NumeroEmpresa.png"))); // NOI18N
        jPanelDatos.add(jLabelIconoNumeroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabelIconoDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Direccion.png"))); // NOI18N
        jPanelDatos.add(jLabelIconoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabelIconoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Correo.png"))); // NOI18N
        jPanelDatos.add(jLabelIconoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabelIconoTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Telefono.png"))); // NOI18N
        jPanelDatos.add(jLabelIconoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabelIconoNacionalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Nacionalidad.png"))); // NOI18N
        jPanelDatos.add(jLabelIconoNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jPanelMain.add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 460, 370));

        jLabelOficina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Oficina.png"))); // NOI18N
        jPanelMain.add(jLabelOficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jButtonSalir.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/eliminar.png"))); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 170, -1));

        jButtonVerDatos.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButtonVerDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Tabla.png"))); // NOI18N
        jButtonVerDatos.setText("VER DATOS");
        jButtonVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDatosActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonVerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        Login login=new Login(); //Creamos una nueva ventana de login para volver a ella
        login.setVisible(true); //La hacemos visible
        dispose();//Cerramos esta ventana
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDatosActionPerformed
        TablaProveedores proveedores=new TablaProveedores(this, true); //Creamos un diálogo modal de la tabla de proveedores
        proveedores.setVisible(true); //Lo hacemos visible
    }//GEN-LAST:event_jButtonVerDatosActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        //Obtenemos todos los datos
        int numeroEmpresa=Integer.parseInt(jTextFieldNumeroEmpresa.getText()); //No hace falta comprobar si es un numero porque si no lo es el boton esta desactivado
        String nombreEmpresa=jTextFieldNombreEmpresa.getText();
        String direccion=jTextFieldDireccion.getText();
        String email=jTextFieldEmail.getText();
        String telefono=jTextFieldTelefono.getText();
        String nacionalidad=jComboBoxNacionalidad.getSelectedItem().toString(); //Pasamos a String el objeto del ComboBox
        String mensaje=""; //Variable para guardar un mensaje que mostrar al insertar o si hay error
        boolean registroValido=true; //Variable para saber si la inserción es correcta o no
        if(contieneNumeros(nombreEmpresa)){ //Si el nombre de la empresa contiene numeros
            registroValido=false; //La inserción no es correcta
            mensaje+="El nombre de la empresa no puede tener numeros\n";
        }
        
        for(Proveedor p:ListaProveedores.getProveedores()){ //Recorremos la lista de proveedores
            if(p.getNumeroProveedor()==numeroEmpresa){ //Si ya existe un proveedor con ese numero
                registroValido=false; //La inserción no es correcta
                mensaje+="Ya existe un proveedor con el numero "+numeroEmpresa+"\n";
            }
        }
        
        if(registroValido){ //Si todo es correcto
            mensaje="Cliente "+nombreEmpresa+" con numero "+numeroEmpresa+" y direccion "+direccion+" insertado.\nEmail: "+email+"   Telefono: "+telefono+"   Nacionalidad: "+nacionalidad;
        JOptionPane.showMessageDialog(this, mensaje,"PROVEEDOR INSERTADO",JOptionPane.INFORMATION_MESSAGE); //Mostramos el mensaje de aviso
        Proveedor p=new Proveedor(numeroEmpresa,nombreEmpresa,direccion,email,telefono,nacionalidad); //Creamos un proveedor con los datos introducidos
        ListaProveedores.anadirProveedor(p); //Añadimos el proveedor a la lista
        limpiarCampos(); //Limpiamos todos los campos
        }
        else JOptionPane.showMessageDialog(this, mensaje,"ERROR INSERCION",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private static boolean contieneNumeros(String s){
        return s.matches(".*\\d+.*"); //Devuelve true si contiene digitos, false si no
    }
    
    
    private void limpiarCampos(){
        //Vaciamos todos los campos de texto y seleccionamos el index por defecto en el ComboBox
        jTextFieldNumeroEmpresa.setText("");
        jTextFieldNombreEmpresa.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelefono.setText("");
        jComboBoxNacionalidad.setSelectedIndex(2);
    }
    private void validationPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_validationPanelStateChanged
        if(validationPanel.getProblem()==null)jButtonInsertar.setEnabled(true); //Si no hay problemas detectados por el validationPanel, activamos el boton
        else jButtonInsertar.setEnabled(false); //Si hay, lo desactivamos
    }//GEN-LAST:event_validationPanelStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerDatos;
    private javax.swing.JComboBox<String> jComboBoxNacionalidad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIconoDireccion;
    private javax.swing.JLabel jLabelIconoEmail;
    private javax.swing.JLabel jLabelIconoNacionalidad;
    private javax.swing.JLabel jLabelIconoNombreEmpresa;
    private javax.swing.JLabel jLabelIconoNumeroEmpresa;
    private javax.swing.JLabel jLabelIconoTelefono;
    private javax.swing.JLabel jLabelNacionalidad;
    private javax.swing.JLabel jLabelNombreEmpresa;
    private javax.swing.JLabel jLabelNumeroEmpresa;
    private javax.swing.JLabel jLabelOficina;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanelDatos;
    private jpanellogo.JPanelLogo jPanelLogo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombreEmpresa;
    private javax.swing.JTextField jTextFieldNumeroEmpresa;
    private javax.swing.JTextField jTextFieldTelefono;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
