/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.gui;

import examen.logica.ListaProveedores;
import examen.logica.Proveedor;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarde
 */
public class TablaProveedores extends javax.swing.JDialog {

    /**
     * Creates new form TablaProveedores
     */
    public TablaProveedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refrescarTabla(); //Llenamos la tabla con datos
    }

    private void refrescarTabla(){
        DefaultTableModel dtm=new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //Hacemos que las celdas no sean editables al hacer doble clic sobre ellas
        }
        };
        dtm.setColumnIdentifiers(new String[]{"Numero proveedor","Nombre empresa","Direccion","Email","Telefono","Nacionalidad"}); //Ponemos nombre a las columnas
        for(Proveedor p:ListaProveedores.getProveedores()){ //Para cada proveedor de la lista
            String[]fila=new String[6]; //Creamos un Array de Strings de longitud 6
            //Añadimos los datos del proveedor a la lista
            fila[0]=p.getNumeroProveedor()+"";
            fila[1]=p.getNombreEmpresa();
            fila[2]=p.getDireccion();
            fila[3]=p.getEmail();
            fila[4]=p.getTelefono();
            fila[5]=p.getNacionalidad();
            dtm.addRow(fila); //Añadimos el array a la tabla
        }
        jTableProveedores.setModel(dtm); //Establecemos el modelo creado como el de la tabla
        
        jScrollPane1.getViewport().setBackground(Color.decode("#8D0000")); //Establecemos el color de fondo del jScrollPane que contiene la tabla
        
        //Apartado visual de la tabla
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.decode("#8D0000")); //Cambiamos el fondo del header
        headerRenderer.setForeground(Color.WHITE); //Cambiamos el color de fuente del header
        headerRenderer.setHorizontalAlignment(JLabel.CENTER); //Centramos el texto del header
        for (int i = 0; i < jTableProveedores.getModel().getColumnCount(); i++) { //Para cada columna
            jTableProveedores.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer); //Establecemos el header al que hemos creado
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProveedores;
    // End of variables declaration//GEN-END:variables
}
