/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut6_actividad3.juego2;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Line2D;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Tarde
 */
public class JuegoPanel extends javax.swing.JPanel {
    private int turno=1;
    private ActionListener listener;
    /**
     * Creates new form JuegoPanel
     */
    public JuegoPanel() {
        initComponents();
        listener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JButton boton=(JButton)e.getSource();
                if(boton.getIcon()==null){ //Si aun no se ha pulsado
                    if(turno==1){
                    boton.setIcon(new ImageIcon(getClass().getResource("/imgs/cruz.png")));
                    turno=2;
                }
                else if(turno==2){
                    boton.setIcon(new ImageIcon(getClass().getResource("/imgs/circulo.png")));
                    turno=1;
                }
                }
            }
        };
        añadirListenerABotones();
    }

    private void añadirListenerABotones(){
        jButton1.addActionListener(listener);
        jButton2.addActionListener(listener);
        jButton3.addActionListener(listener);
        jButton4.addActionListener(listener);
        jButton5.addActionListener(listener);
        jButton6.addActionListener(listener);
        jButton7.addActionListener(listener);
        jButton8.addActionListener(listener);
        jButton9.addActionListener(listener);
        
    }
    @Override
    protected void paintComponent(Graphics g) {
        pintarTablero(g);
    }
    private void pintarTablero(Graphics g){
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(5));
        Line2D lin = new Line2D.Float(this.getWidth()/3,0,this.getWidth()/3,this.getHeight());
        g2.draw(lin);
        lin = new Line2D.Float(this.getWidth()/3*2,0,this.getWidth()/3*2,this.getHeight());
        g2.draw(lin);
        lin = new Line2D.Float(0,this.getHeight()/3,this.getWidth(),this.getHeight()/3);
        g2.draw(lin);
        lin = new Line2D.Float(0,this.getHeight()/3*2,this.getWidth(),this.getHeight()/3*2);
        g2.draw(lin);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(3, 3));
        add(jButton1);
        add(jButton2);
        add(jButton3);
        add(jButton4);
        add(jButton5);
        add(jButton6);
        add(jButton7);
        add(jButton8);
        add(jButton9);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
