/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1ut6_actividad3.juego2;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;

/**
 *
 * @author Tarde
 */
public class JuegoPanel extends javax.swing.JPanel {
    private int grosor=15;
    public static Color color=Color.RED;
    /**
     * Creates new form JuegoPanel
     */
    public JuegoPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        pintarTablero(g);
    }
    private void pintarTablero(Graphics g){
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(5));
        Line2D lin = new Line2D.Float(this.getWidth()/3,0,this.getWidth()/3,this.getHeight());
        g2.draw(lin);
        lin = new Line2D.Float(this.getWidth()/3*2,0,this.getWidth()/3*2,this.getHeight());
        g2.draw(lin);
        lin = new Line2D.Float(0,this.getHeight()/3,this.getWidth(),this.getHeight()/3);
        g2.draw(lin);
        lin = new Line2D.Float(0,this.getHeight()/3*2,this.getWidth(),this.getHeight()/3*2);
        g2.draw(lin);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Graphics g=getGraphics(); //Importante obtener los graficos del área de dibujo y no de la ventana
        g.setColor(color); //Pintaremos de color negro
        g.fillOval(evt.getX(),evt.getY(),grosor,grosor); 
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
