/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad4;

import java.awt.Color;

/**
 *
 * @author Daniel Monforte Ibias
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPregunta1 = new javax.swing.ButtonGroup();
        buttonGroupPregunta2 = new javax.swing.ButtonGroup();
        buttonGroupPregunta3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelPregunta1 = new javax.swing.JLabel();
        jLabelPregunta2 = new javax.swing.JLabel();
        jLabelPregunta3 = new javax.swing.JLabel();
        jLabelPregunta4 = new javax.swing.JLabel();
        jRadioButtonPregunta1A = new javax.swing.JRadioButton();
        jRadioButtonPregunta1B = new javax.swing.JRadioButton();
        jRadioButtonPregunta1C = new javax.swing.JRadioButton();
        jRadioButtonPreguntaD = new javax.swing.JRadioButton();
        jRadioButtonPregunta2A = new javax.swing.JRadioButton();
        jRadioButtonPregunta2B = new javax.swing.JRadioButton();
        jRadioButtonPregunta2C = new javax.swing.JRadioButton();
        jRadioButtonPregunta2D = new javax.swing.JRadioButton();
        jRadioButtonPregunta3A = new javax.swing.JRadioButton();
        jRadioButtonPregunta3B = new javax.swing.JRadioButton();
        jRadioButtonPregunta3C = new javax.swing.JRadioButton();
        jRadioButtonPregunta3D = new javax.swing.JRadioButton();
        jButtonCorregir = new javax.swing.JButton();
        jCheckBoxPregunta4A = new javax.swing.JCheckBox();
        jCheckBoxPregunta4B = new javax.swing.JCheckBox();
        jCheckBoxPregunta4C = new javax.swing.JCheckBox();
        jCheckBoxPregunta4D = new javax.swing.JCheckBox();
        jLabelAciertos = new javax.swing.JLabel();
        jLabelResultado1 = new javax.swing.JLabel();
        jLabelResultado2 = new javax.swing.JLabel();
        jLabelResultado3 = new javax.swing.JLabel();
        jLabelResultado4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 228));
        jPanel1.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Ingrese las respuestas correctas");
        jPanel1.add(jLabelTitulo);
        jLabelTitulo.setBounds(190, 30, 390, 29);

        jLabelPregunta1.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabelPregunta1.setText("4*6+3+2*2");
        jPanel1.add(jLabelPregunta1);
        jLabelPregunta1.setBounds(20, 120, 80, 17);

        jLabelPregunta2.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabelPregunta2.setText("Nombre del quinto planeta");
        jPanel1.add(jLabelPregunta2);
        jLabelPregunta2.setBounds(20, 170, 200, 17);

        jLabelPregunta3.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabelPregunta3.setText("Palabra con error ortográfico");
        jPanel1.add(jLabelPregunta3);
        jLabelPregunta3.setBounds(20, 220, 217, 17);

        jLabelPregunta4.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabelPregunta4.setText("Sinónimos de inteligente");
        jPanel1.add(jLabelPregunta4);
        jLabelPregunta4.setBounds(20, 270, 186, 17);

        jRadioButtonPregunta1A.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta1.add(jRadioButtonPregunta1A);
        jRadioButtonPregunta1A.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta1A.setText("58");
        jPanel1.add(jRadioButtonPregunta1A);
        jRadioButtonPregunta1A.setBounds(260, 120, 60, 25);

        jRadioButtonPregunta1B.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta1.add(jRadioButtonPregunta1B);
        jRadioButtonPregunta1B.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta1B.setText("34");
        jPanel1.add(jRadioButtonPregunta1B);
        jRadioButtonPregunta1B.setBounds(360, 120, 60, 25);

        jRadioButtonPregunta1C.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta1.add(jRadioButtonPregunta1C);
        jRadioButtonPregunta1C.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta1C.setText("31");
        jPanel1.add(jRadioButtonPregunta1C);
        jRadioButtonPregunta1C.setBounds(460, 120, 60, 25);

        jRadioButtonPreguntaD.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta1.add(jRadioButtonPreguntaD);
        jRadioButtonPreguntaD.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPreguntaD.setText("40");
        jPanel1.add(jRadioButtonPreguntaD);
        jRadioButtonPreguntaD.setBounds(560, 120, 60, 25);

        jRadioButtonPregunta2A.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta2.add(jRadioButtonPregunta2A);
        jRadioButtonPregunta2A.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta2A.setText("Marte");
        jPanel1.add(jRadioButtonPregunta2A);
        jRadioButtonPregunta2A.setBounds(260, 170, 70, 25);

        jRadioButtonPregunta2B.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta2.add(jRadioButtonPregunta2B);
        jRadioButtonPregunta2B.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta2B.setText("Júpiter");
        jPanel1.add(jRadioButtonPregunta2B);
        jRadioButtonPregunta2B.setBounds(360, 170, 80, 25);

        jRadioButtonPregunta2C.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta2.add(jRadioButtonPregunta2C);
        jRadioButtonPregunta2C.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta2C.setText("Tierra");
        jPanel1.add(jRadioButtonPregunta2C);
        jRadioButtonPregunta2C.setBounds(460, 170, 70, 25);

        jRadioButtonPregunta2D.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta2.add(jRadioButtonPregunta2D);
        jRadioButtonPregunta2D.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta2D.setText("Saturno");
        jPanel1.add(jRadioButtonPregunta2D);
        jRadioButtonPregunta2D.setBounds(560, 170, 83, 25);

        jRadioButtonPregunta3A.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta3.add(jRadioButtonPregunta3A);
        jRadioButtonPregunta3A.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta3A.setText("Ola");
        jPanel1.add(jRadioButtonPregunta3A);
        jRadioButtonPregunta3A.setBounds(260, 220, 60, 25);

        jRadioButtonPregunta3B.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta3.add(jRadioButtonPregunta3B);
        jRadioButtonPregunta3B.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta3B.setText("Desición");
        jPanel1.add(jRadioButtonPregunta3B);
        jRadioButtonPregunta3B.setBounds(360, 220, 90, 25);

        jRadioButtonPregunta3C.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta3.add(jRadioButtonPregunta3C);
        jRadioButtonPregunta3C.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta3C.setText("Hay");
        jPanel1.add(jRadioButtonPregunta3C);
        jRadioButtonPregunta3C.setBounds(460, 220, 70, 25);

        jRadioButtonPregunta3D.setBackground(new java.awt.Color(255, 255, 228));
        buttonGroupPregunta3.add(jRadioButtonPregunta3D);
        jRadioButtonPregunta3D.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jRadioButtonPregunta3D.setText("Ahí");
        jPanel1.add(jRadioButtonPregunta3D);
        jRadioButtonPregunta3D.setBounds(560, 220, 60, 25);

        jButtonCorregir.setBackground(new java.awt.Color(210, 255, 210));
        jButtonCorregir.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButtonCorregir.setText("Corregir");
        jButtonCorregir.setFocusPainted(false);
        jButtonCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorregirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCorregir);
        jButtonCorregir.setBounds(190, 320, 400, 30);

        jCheckBoxPregunta4A.setBackground(new java.awt.Color(255, 255, 228));
        jCheckBoxPregunta4A.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jCheckBoxPregunta4A.setText("Sagaz");
        jPanel1.add(jCheckBoxPregunta4A);
        jCheckBoxPregunta4A.setBounds(260, 270, 80, 25);

        jCheckBoxPregunta4B.setBackground(new java.awt.Color(255, 255, 228));
        jCheckBoxPregunta4B.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jCheckBoxPregunta4B.setText("Listo");
        jPanel1.add(jCheckBoxPregunta4B);
        jCheckBoxPregunta4B.setBounds(360, 270, 70, 25);

        jCheckBoxPregunta4C.setBackground(new java.awt.Color(255, 255, 228));
        jCheckBoxPregunta4C.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jCheckBoxPregunta4C.setText("Lerdo");
        jPanel1.add(jCheckBoxPregunta4C);
        jCheckBoxPregunta4C.setBounds(460, 270, 70, 25);

        jCheckBoxPregunta4D.setBackground(new java.awt.Color(255, 255, 228));
        jCheckBoxPregunta4D.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jCheckBoxPregunta4D.setText("Astuto");
        jPanel1.add(jCheckBoxPregunta4D);
        jCheckBoxPregunta4D.setBounds(560, 270, 80, 25);

        jLabelAciertos.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jPanel1.add(jLabelAciertos);
        jLabelAciertos.setBounds(340, 360, 120, 30);

        jLabelResultado1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabelResultado1.setToolTipText("");
        jPanel1.add(jLabelResultado1);
        jLabelResultado1.setBounds(660, 120, 80, 20);

        jLabelResultado2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(jLabelResultado2);
        jLabelResultado2.setBounds(660, 170, 80, 20);

        jLabelResultado3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(jLabelResultado3);
        jLabelResultado3.setBounds(660, 220, 80, 20);

        jLabelResultado4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(jLabelResultado4);
        jLabelResultado4.setBounds(660, 270, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorregirActionPerformed
        int aciertos=0; //Número de aciertos del usuario
        if (jRadioButtonPregunta1C.isSelected()){ //La correcta es la C. Si el usuario la ha elegido
            aciertos++; //Incrementamos los aciertos
            jLabelResultado1.setText("Correcto"); //Su resultado es correcto
            jLabelResultado1.setForeground(Color.green); //El resultado se mostrará en verde
        }
        else{ //Si la respuesta del usuario no es correcta
            jLabelResultado1.setText("Incorrecto"); //Su resultado es incorrecto
            jLabelResultado1.setForeground(Color.red); //El resultado se mostrará en rojo
        }
        if (jRadioButtonPregunta2B.isSelected()){ //La correcta es la B. Si el usuario la ha elegido
            aciertos++; //Incrementamos los aciertos
            jLabelResultado2.setText("Correcto"); //Su resultado es correcto
            jLabelResultado2.setForeground(Color.green); //El resultado se mostrará en verde
        }
        else{
            jLabelResultado2.setText("Incorrecto"); //Su resultado es incorrecto
            jLabelResultado2.setForeground(Color.red); //El resultado se mostrará en rojo
        }
        if (jRadioButtonPregunta3B.isSelected()){ //La correcta es la B. Si el usuario la ha elegido
            aciertos++; //Incrementamos los aciertos
            jLabelResultado3.setText("Correcto"); //Su resultado es correcto
            jLabelResultado3.setForeground(Color.green); //El resultado se mostrará en verde
        }
        else{
            jLabelResultado3.setText("Incorrecto"); //Su resultado es incorrecto
            jLabelResultado3.setForeground(Color.red); //El resultado se mostrará en rojo
        }
        if (jCheckBoxPregunta4A.isSelected() && jCheckBoxPregunta4B.isSelected() && jCheckBoxPregunta4D.isSelected() && !jCheckBoxPregunta4C.isSelected()){ //Las correctas son A, B y D. Si el usuario las ha elegido
            aciertos++; //Incrementamos los aciertos
            jLabelResultado4.setText("Correcto"); //Su resultado es correcto
            jLabelResultado4.setForeground(Color.green); //El resultado se mostrará en verde
        }
        else{ //Si no ha marcado las 3 correctas
            jLabelResultado4.setText("Incorrecto"); //Su resultado es incorrecto
            jLabelResultado4.setForeground(Color.red); //El resultado se mostrará en rojo
        }
        jLabelAciertos.setText("Aciertos: "+aciertos+"/4"); //Mostramos los aciertos del usuario
    }//GEN-LAST:event_jButtonCorregirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPregunta1;
    private javax.swing.ButtonGroup buttonGroupPregunta2;
    private javax.swing.ButtonGroup buttonGroupPregunta3;
    private javax.swing.JButton jButtonCorregir;
    private javax.swing.JCheckBox jCheckBoxPregunta4A;
    private javax.swing.JCheckBox jCheckBoxPregunta4B;
    private javax.swing.JCheckBox jCheckBoxPregunta4C;
    private javax.swing.JCheckBox jCheckBoxPregunta4D;
    private javax.swing.JLabel jLabelAciertos;
    private javax.swing.JLabel jLabelPregunta1;
    private javax.swing.JLabel jLabelPregunta2;
    private javax.swing.JLabel jLabelPregunta3;
    private javax.swing.JLabel jLabelPregunta4;
    private javax.swing.JLabel jLabelResultado1;
    private javax.swing.JLabel jLabelResultado2;
    private javax.swing.JLabel jLabelResultado3;
    private javax.swing.JLabel jLabelResultado4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonPregunta1A;
    private javax.swing.JRadioButton jRadioButtonPregunta1B;
    private javax.swing.JRadioButton jRadioButtonPregunta1C;
    private javax.swing.JRadioButton jRadioButtonPregunta2A;
    private javax.swing.JRadioButton jRadioButtonPregunta2B;
    private javax.swing.JRadioButton jRadioButtonPregunta2C;
    private javax.swing.JRadioButton jRadioButtonPregunta2D;
    private javax.swing.JRadioButton jRadioButtonPregunta3A;
    private javax.swing.JRadioButton jRadioButtonPregunta3B;
    private javax.swing.JRadioButton jRadioButtonPregunta3C;
    private javax.swing.JRadioButton jRadioButtonPregunta3D;
    private javax.swing.JRadioButton jRadioButtonPreguntaD;
    // End of variables declaration//GEN-END:variables
}
