/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad3.gui;

import actividad3.logica.ListaPalabras;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Monforte Ibias
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        refrescarTabla(); //Refrescamos la tabla en un principio para darle la apariencia correcta
        establecerColoresJOptionPane(); //Damos formato a los JOptionPane que se vayan a mostrar
    }

    private void refrescarTabla(){
        DefaultTableModel dtm=new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; //Hacemos que las celdas no sean editables al hacer doble clic sobre ellas
        }
        };
        dtm.setColumnIdentifiers(new String[]{"Palabras"}); //Ponemos nombre a la columna
        ArrayList<String>listaPalabras=ListaPalabras.getPalabras(); //Obtenemos el ArrayList de palabras
        for(String palabra:listaPalabras){ //Para cada palabra del ArrayList
            String[]fila=new String[1]; //Creamos un Array de Strings de longitud 1
            fila[0]=palabra; //El valor del array es la palabra
            dtm.addRow(fila); //Añadimos el array a la tabla
        }
        jTablePalabras.setModel(dtm); //Establecemos el modelo creado como el de la tabla
        
        jScrollPaneTable.getViewport().setBackground(new Color(0xCCCCFF)); //Establecemos el color de fondo del jScrollPane que contiene la tabla
        
        //Apartado visual de la tabla
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(0xAAAAAFF)); //Cambiamos el fondo del header
        headerRenderer.setHorizontalAlignment(JLabel.CENTER); //Centramos el texto del header
        for (int i = 0; i < jTablePalabras.getModel().getColumnCount(); i++) { //Para cada columna
            jTablePalabras.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer); //Establecemos el header al que hemos creado
        }
    }
    private void establecerColoresJOptionPane(){
        UIManager UI=new UIManager();
        UIManager.put("control", new Color(0xEBEBFF)); //Cambia todos los fondos del JOptionPane
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldPalabra = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTablePalabras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(235, 235, 255));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelTitulo.setText("Ingrese palabra:");
        jPanel.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, -1, -1));

        jTextFieldPalabra.setBackground(new java.awt.Color(204, 204, 255));
        jTextFieldPalabra.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jPanel.add(jTextFieldPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 30));

        jButtonIngresar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonIngresar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setFocusPainted(false);
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        jButtonMostrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonMostrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.setFocusPainted(false);
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, -1));

        jScrollPaneTable.setOpaque(false);

        jTablePalabras.setBackground(new java.awt.Color(204, 204, 255));
        jTablePalabras.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jTablePalabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePalabras.setRowSelectionAllowed(false);
        jScrollPaneTable.setViewportView(jTablePalabras);

        jPanel.add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 270, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        String palabra=jTextFieldPalabra.getText(); //Obtenemos la palabra
        jTextFieldPalabra.setText(""); //Vaciamos el campo de texto
        if (!comprobarValida(palabra) || palabra.length()>10){ //Si contiene números o símbolos, o si mide más de 10 letras, no es válida
            AlertaPalabra alerta=new AlertaPalabra(this,true); //Avisamos al usuario con un diálogo de error
            alerta.setVisible(true);
        }
        else{ //Si cumple los requisitos
            ListaPalabras.anadirPalabra(palabra); //La añadimos a la lista
            
        }
        
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        refrescarTabla(); //Refrescamos la tabla
        comprobarPalabras(); //Comprobamos si hay palabras o no
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    public static boolean comprobarValida(String palabra){ //Este método comprueba si el parámetro que recibe es una plaabra válida
        return palabra.matches("[a-zA-Z]+"); //Devuelve true si la palabara solo contiene letras
    }
    
    
    
    public void comprobarPalabras(){
        if (ListaPalabras.getPalabras().size()==0){ //Si el tamaño del ArrayList es 0, no hay palabras
           JOptionPane.showMessageDialog(this, "No hay palabras ingresadas", "Aviso", JOptionPane.INFORMATION_MESSAGE); //Mostramos un mensaje
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTablePalabras;
    private javax.swing.JTextField jTextFieldPalabra;
    // End of variables declaration//GEN-END:variables
}
