/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad4_1.gui;

import java.applet.AudioClip;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Danim2205
 */
public class InicioSesion extends javax.swing.JFrame {
    AudioClip sound=java.applet.Applet.newAudioClip(getClass().getResource("/actividad4_1/sounds/Okay.wav")); //Sonido inicializado
    private static String usuario; //Variable para guardar el usuario
    private static String password; //Variable para guardar la password
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/actividad4_1/imgs/Logo.png")).getImage()); //Icono de la aplicación
        establecerColoresJOptionPane(); //Color de los JOptionPane
    }

    public static String getUsuario() {
        return usuario;
    }

    public static String getPassword() {
        return password;
    }

    private void establecerColoresJOptionPane(){
        UIManager UI=new UIManager();
        UIManager.put("control", Color.WHITE); //Cambia todos los fondos del JOptionPane
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelLogoCineRibera = new jpanellogocineribera.JPanelLogoCineRibera();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonVerPassword = new javax.swing.JButton();
        jButtonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel.add(jPanelLogoCineRibera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabelUsuario.setText("USUARIO:");
        jPanel.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabelPassword.setText("PASSWORD:");
        jPanel.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jTextFieldUsuario.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 310, -1));

        jPasswordField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 310, -1));

        jButtonVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4_1/imgs/Ojo.png"))); // NOI18N
        jButtonVerPassword.setContentAreaFilled(false);
        jButtonVerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPasswordActionPerformed(evt);
            }
        });
        jPanel.add(jButtonVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 30, 30));

        jButtonIngresar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIngresar.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("INGRESAR");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 520, -1));

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 623, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPasswordActionPerformed
        if(jPasswordField.getEchoChar()==(char)0) jPasswordField.setEchoChar('\u25cf'); //Si la password es visible, la ocultamos con el carácter especial
        else jPasswordField.setEchoChar((char)0); //Si la password no es visible, la hacemos visible
    }//GEN-LAST:event_jButtonVerPasswordActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        usuario=jTextFieldUsuario.getText(); //Obtenemos el usuario
        char passwordArray[]=jPasswordField.getPassword(); //Obtenemos el array de chars de la password
        password=new String(passwordArray); //Pasamos la password a String
        boolean datosValidos=true;
        if(usuario.equals("") || password.equals("")){ //Si algún campo está vacío
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacíos", "Error campos", JOptionPane.ERROR_MESSAGE); //Avisamos al usuario
            datosValidos=false; //No entramos
        }
        if(usuario.length()>10){ //Si el usuario mide más de 10 caracteres
            JOptionPane.showMessageDialog(this, "El usuario no puede medir más de 10 caracteres", "Error longitud usuario", JOptionPane.ERROR_MESSAGE); //Avisamos al usuario
            datosValidos=false; //No entramos
        }
        if(datosValidos){ //Si los datos son válidos
            sound.play(); //Reproducimos el sonido
            JOptionPane.showMessageDialog(this, "Bienvenido a Cine Ribera, "+usuario, "Inicio de sesión", JOptionPane.INFORMATION_MESSAGE); //Informamos al usuario
            PantallaPrincipal principal=new PantallaPrincipal(); //Creamos la pantalla principal
            principal.setVisible(true); //La hacemos visible
            dispose();//Destruimos esta pantalla
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonVerPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel;
    private jpanellogocineribera.JPanelLogoCineRibera jPanelLogoCineRibera;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
